### ISSUE TITLE
Option to reorder the checkout steps

### ISSUE THREAD

**Issue by Wassini** [dynamicweb/DynamicWeb#10]
Minor inconvenience, but then adding a new step to an order cart checkout it is only possible to add the the end of the list. So if you have to add a new first step, you have to delete all steps and add it again.

![image](https://github.com/dynamicweb/DynamicWeb/assets/17749701/28014033-0752-4dd7-906d-be0c68b816cf)

**Comment by nicped** [comment]
Yes - will just see if this is missing from this particular place or it is a lack of feature in the control it self.

**Comment by aksschnell** [comment]
Any updates on this?

**Comment by nicped** [comment]
Yes - it was released yesterday with 10.4:

![image](https://github.com/dynamicweb/DynamicWeb/assets/3715307/d5a4c1fb-8798-4e74-9b2f-1001295a8926)
