### ISSUE TITLE
"Table shema errors"

### ISSUE THREAD

**Issue by dwlhs** [dynamicweb/DynamicWeb#100]
Hi :)

Can we have this label changed? We're rarely talking about "errors", more likely we are talking about "changes" :)

![image](https://github.com/dynamicweb/DynamicWeb/assets/31095845/cc265b1f-925e-4636-9289-b7b153d03b40)

Br.
Lars

**Comment by DynamicRas** [comment]
Hi,

Good point! We will change it.

BR Rasmus Sanggaard
