### ISSUE TITLE
Skipped rows marked as errors

### ISSUE THREAD

**Issue by dwlhs** [dynamicweb/DynamicWeb#101]
Hi :)

In the Integration tool we can set up the activity to skip duplicate rows. When doing that, the log is cluttered with error icons, and the messages even refers to the skipped record as a "failed row":

![image](https://github.com/dynamicweb/DynamicWeb/assets/31095845/649bf4cf-0b4a-45a6-af83-0f98ca5ecc37)

It is not a failed row, because the activity was configured to skip it, and customers get uncomfortable when seeing error signs all over the place.

Could you mark them as completed and remove the "failed" phrase in the log?

![image](https://github.com/dynamicweb/DynamicWeb/assets/31095845/3f1986ee-a058-4b83-bd67-6da3678f926a)

Thanks :)

Br.
Lars

**Comment by DynamicRas** [comment]
Hi,

Agree. We will take a look at how to improve the log overview when skipping rows. 

BR Rasmus Sanggaard
