### ISSUE TITLE
Cache is cleared when integration activity fails

### ISSUE THREAD

**Issue by dwlhs** [dynamicweb/DynamicWeb#102]
Hi :)

When you set an activity to clear the cache one or more caches, it does so even when the activity fails:

![image](https://github.com/dynamicweb/DynamicWeb/assets/31095845/dbec9dcd-f02a-4e65-b867-9b6d52bca997)

Not clearing the cache would probably be the right thing to do  in this scenario. Not a huge issue, though :)

Br.
Lars

**Comment by DynamicRas** [comment]
Hi,

We have already implemented a feature that allows you to choose not to clear caches if no rows are updated or if an activity fails. This feature is available in version 10.6 and will be rolled out to all providers very soon.

BR Rasmus Sanggaard

**Comment by dwlhs** [comment]
Just thinking whether to loose the checkbox and clear the cache, if the activity completes successfully and otherwise don't clear the cache :)

Br.
Lars
