### ISSUE TITLE
More improvement to Integration mapping screen

### ISSUE THREAD

**Issue by Wassini** [dynamicweb/DynamicWeb#104]
1. Could we have an icon or something that shows that a table mapping contains a "Condition" e.g. a "Filter Icon" in the table row:
![image](https://github.com/dynamicweb/DynamicWeb/assets/17749701/e2f42c8f-c2a8-44d8-9ed6-91b89595f899)

2. Can we have the LED icons changed to a checkbox. I keep thinking that there is an error, when I see a red light.
![image](https://github.com/dynamicweb/DynamicWeb/assets/17749701/7aabd3fe-ad04-432e-ac80-fc7ce1cab536)

**Comment by DynamicRas** [comment]
Hi,

1. Sure thing. Here you go:
![image](https://github.com/dynamicweb/DynamicWeb/assets/130552435/cd5de09e-bd6c-482e-9041-5d0ba0865451)
All jokes aside, it should already be there next to the source table. 
2. It is a common UI issue that I know the frontend team is looking into, I will mention it again.

BR Rasmus Sanggaard
