### ISSUE TITLE
Save Firehose result to Excel

### ISSUE THREAD

**Issue by dwlhs** [dynamicweb/DynamicWeb#106]
Hi :)

From time to time we need to generate a report based on a query on the database. It would be amazing if we could download the result of a query in the SQL Firehose as an Excel spreadsheet.

Br.
Lars

**Comment by DynamicRas** [comment]
Hi, 

Makes sense to have a download option as we have it in the Integration area for a response. We will take a look at the possibilities. 

BR Rasmus Sanggaard
