### ISSUE TITLE
Improved log information in OData provider

### ISSUE THREAD

**Issue by dwlhs** [dynamicweb/DynamicWeb#107]
Hi :)

We were experiencing some issues retrieving data from an OData entity in Business Central. The log just indicated HttpStatusCode "Conflict":

![image](https://github.com/dynamicweb/DynamicWeb/assets/31095845/839429c9-ae6d-40de-9b91-d93da601b78e)

Please include the http error number, in this case 409.

We were able to reproduce the error using Postman and received this response:

{
    "error": {
        "code": "Internal_ServerError",
        "message": "The activity was deadlocked with another user. Please retry the activity.  CorrelationId:  475d489e-dc25-4f56-90e8-0a2d110af502."
    }
}

This was indeed very helpful, so we were able to trace the error in BC.

Please include this response information in the log as well, when the http status code is different from 200.

Br.
Lars

**Comment by DynamicRas** [comment]
Hi,

We always try to make the most information present in the logs, I will add the task to the backlog to get this info in the log as well. 

BR Rasmus Sanggaard

**Comment by dwlhs** [comment]
Great, thanks :)
