### ISSUE TITLE
Notification emails in Integration

### ISSUE THREAD

**Issue by dwlhs** [dynamicweb/DynamicWeb#108]
Hi :)

In the integration setup, we can add notification emails individual scheduled tasks, individual activities and individual instances of live integration. We have to specify sender, subjects, recipients etc. for each notification setup, and that indeed can result in lots of manual work.

It would be great if e.g. we could set up automation emails with a recipient list, so we would have one place to configure this, not to mention, one place to maintain this on the longer run.

Br.
Lars

**Comment by DynamicRas** [comment]
Hi,

It is something that could make sense to look at, but it would be a platform thing and not only for integration. I have added it to the backlog for further investigations. Thanks.

BR Rasmus Sanggaard

**Comment by dwlhs** [comment]
Yes, I agree :)
