### ISSUE TITLE
Improve image optimization to follow the latest recommendations for rendering images on the web (LCP & CLS metrics)

### ISSUE THREAD

**Issue by daniel-voicu-dev** [dynamicweb/DynamicWeb#11]
**Is your feature request related to a problem? Please describe.**
The current partial to render an image(Image.cshtml) does not output an optimized image, but rather an image that uses Bootstrap ratio to fake a ratio. There are unnecessary attributes like _decoding_ with little impact on rendering while other attributes that are recommended are missing: fetchpriority(if image is loaded above the fold), aspect ratio inline style, width and height.

Also, _doNotUseGetimage_ parameter does not make sense if image optimization is prioritized since without passing the required parameters (width, ratio or height) you can never achieve good LCP or CLS scores.

**Describe the solution you'd like**
1. Introducing the required attributes and values to improve LCP and CLS: width, height, inline aspect-ratio CSS property, fetchpriority and maybe a ratio attribute that could be used, so the height can be calculated rather than set.
2. If possible, have a preload link to be rendered if the image is above the fold. With the current AddHeader method, you can not take advantage of preloading images that uses the srcset attribute, since it will always get the lowest image. If you remove the srcset attribute, it will only take the biggest one. I remember hearing that Snippets were not performant in Rapido but AddHeader method makes impossible preloading images in an optimal way. Example:
```c#
Dynamicweb.Context.Current.Response.AddHeader("link", $"<{src}>; rel=preload; as=image; imagesizes=100vw; imagesrcset={srcset}")
```
3. Generate dynamic srcset values only for widths smaller or equal to the file that is used (this means a width & ratio property wherever an image can be uploaded)
4. The Image.cshtml take into consideration the GridRowColumnCount to render the sizes attribute, which might not be relevant at all. If you want to have an optimized image, you want the image to be as close as possible to the rendered image. Example: I want to use a 1000px wide image in a 3 column context. This image currently will be rendered with sizes being 33vw. With the current model, the 33vw works because you are upsizing the image to 1920 by default then getting the lower and image by having the 33vw value. This will not work with a more optimized model where you can upload an image and set the width and ratio of the image you want to see in the frontend while not generating srcset attributes higher than the current input width. In this case, the GridRowColumnCount will not get the correct image from srcset.

**Describe alternatives you've considered**

I've created a file based on Image.cshtml without attributes I do not need. I've kept the column property since it makes sense to have it, but I did not link it to GridRowColumnCount when I used it in a custom Paragraph. This example has no preload link generated for "abovethefold" property, since I did not know how to do that.

```c#
@inherits Dynamicweb.Rendering.ViewModelTemplate<Dynamicweb.Frontend.FileViewModel>

@functions {
	private static string RenderImageSrcSetAttribute(string src, double width, double ratio, int quality)
	{
		double[] breakpoints = { 412, 768, 1024, 1280, 1600, 1920 };
		string srcUrlEncode = Dynamicweb.Context.Current.Server.UrlEncode(src);
    
		return breakpoints.ToList().Where(x => x <= width).Aggregate("", (current, breakpoint) => current + ("/Admin/Public/GetImage.ashx?width=" + breakpoint + "&height=" + Convert.ToInt32(Math.Floor(breakpoint / ratio)) + "&crop=7&format=webP&quality=" + quality + "&FillCanvas=false&DoNotUpscale=true&image=" + srcUrlEncode + " " + breakpoint + "w,"));
	}

}

@if (!string.IsNullOrEmpty(Model.Path))
{
	string imagePath = Model?.Path ?? "";
	string imagePathUrlEncoded = Dynamicweb.Context.Current.Server.UrlEncode(imagePath);

	string imageQuality = GetViewParameterInt32("quality") > 0 ? $"&quality={GetViewParameterInt32("quality")}" : "";
	double imageWidth = GetViewParameterDouble("width") > 0 ? GetViewParameterDouble("width") : 1920;
	int imageHeight = GetViewParameterInt32("height") > 0 ? GetViewParameterInt32("height") : 1920;
	double imageRatio = GetViewParameterDouble("ratio") > 0 ? GetViewParameterDouble("ratio") : 1;
	int quality = GetViewParameterInt32("quality") > 0 ? GetViewParameterInt32("quality") : 95;

	string imgSizeSelector = "100vw";
	bool isFullScreenWidth = GetViewParameterBoolean("fullwidth");
	if (isFullScreenWidth)
	{
		imgSizeSelector = "100vw";
	}
	else
	{
		int imageColumnCount = GetViewParameterInt32("columns");
		if (imageColumnCount == 1)
		{
			imgSizeSelector = "100vw";
		}
		else if (imageColumnCount == 2)
		{
			imgSizeSelector = "50vw";
		}
		else if (imageColumnCount == 3)
		{
			imgSizeSelector = "33vw";
		}
		else if (imageColumnCount == 4)
		{
			imgSizeSelector = "25vw";
		}
		else if (imageColumnCount == 6)
		{
			imgSizeSelector = "17vw";
		}
	}

	string srcset = RenderImageSrcSetAttribute(imagePath,imageWidth,imageRatio,quality);
	

	@* Image sizes + a fallback image *@
	string imagePathFallBack = $"/Admin/Public/GetImage.ashx?image={imagePathUrlEncoded}&width={imageWidth}&height={imageHeight}&format=webp{imageQuality}&quality={quality}&crop=7&FillCanvas=false&DoNotUpscale=true";

	@* attributes to send to the image tag *@
	string loading = !string.IsNullOrEmpty(GetViewParameterString("abovethefold")) ? "fetchpriority=\"high\"" : "loading=\"lazy\"";
	

	var cssClass = GetViewParameter("cssClass");
	var itemprop = GetViewParameter("itemprop");
	var style = GetViewParameter("style");
	string alt = GetViewParameterString("alt");
	var id = GetViewParameter("id"); //	GetViewParameter returns null if no value is found leaving out the id attribute if no value is present for this parameter.

	if (imagePath.EndsWith(".svg", StringComparison.OrdinalIgnoreCase))
	{
		<div class="icon-auto">
			@ReadFile(Model.Path)
		</div>
	}
	else
	{
		<img srcset="@srcset"
			 src="@imagePathFallBack"
			 sizes="(max-width: 992px) 100vw, @imgSizeSelector"
			 @loading
			 class="@cssClass"
			 style="aspect-ratio: @imageWidth / @imageHeight; @style"
			 alt="@alt"
			 id="@id"
			 itemprop="@itemprop"
			>
	}
}

```

**Comment by nicped** [comment]
Thank you for the elaborate request with good explanations.
We are in the process of developing Swift 2.0 where will change parts of the implementation and part of that will be a new imageselector for the backend and a new imageviewmodel in the frontend. As part of that we will see how much of this we can add to the new implementation.
We have also been looking at the above the fold loading (we are also using loading=lazy above the fold) but it is difficult to detect server side. At least precisely.

**Comment by daniel-voicu-dev** [comment]
Indeed, you can't detect above the content server-side precisely, but it should be an option when images are involved and that option to be controlled by the content manager. Since content is contextual, I think only having the option is all that should be expected from a web solution. In the end, the content manager is responsible for the content and the platform is responsible only to give options to achieve what the content manager wants to do.

**Comment by daniel-voicu-dev** [comment]
@nicped I don't know if I should have closed this issue myself. If I shouldn't, please open it for later referance. Thank you.

**Comment by nicped** [comment]
I have it noted. so this is fine. And a setting to control above/under the fold could be a solution
