### ISSUE TITLE
Add unit to order line field selector

### ISSUE THREAD

**Issue by dwlhs** [dynamicweb/DynamicWeb#110]
Hi :)

The UOM is not available in the field selector for orderlines:

![image](https://github.com/user-attachments/assets/b147e2e8-ee70-4d64-9cb5-783fd764f593)

Could you add it, please? Thanks :)

Br.
Lars

**Comment by DynamicRas** [comment]
Hi,

In probably 10.7 is will be possible to make screen configs for list widget, then you can customise the widget as you want for specific users / groups. 

BR Rasmus Sanggaard
