### ISSUE TITLE
Order states in order management

### ISSUE THREAD

**Issue by dwlhs** [dynamicweb/DynamicWeb#111]
Hi :)

The "Order states" section of an order gives the impression that it is a sequential workflow the order needs to to go through:

![image](https://github.com/user-attachments/assets/95d33559-eda0-4a04-bd84-2c5b8dfa11e4)

But this is not the case as the individual states just indicate which state the order is in. Here, we have states "Rejected" and "Deleted", which is not a favorable state in a workflow for an order, and we also have a state indicating that order transfer to ERP failed.

I suggest removing this section from the UI.

Also, in the top right corner, we have a "Completed" flag (2). The value of this field is adapted from the OrderComplete field in the database, which indicates whether it is an order or a cart. Since the order is in the "Orders" section, it means that it is complete, i.e., submitted as an order. In the "Carts" section it is red, because it is not yet completed as an order, which is why it is in "Carts":

![image](https://github.com/user-attachments/assets/5315d507-baf7-4570-ab90-4b12159aa139)

I suggest removing that flag from the UI and rely on the "Orders" and "Carts" sections.

Br.
Lars

**Comment by DynamicRas** [comment]
Hi, 

Completed flag is on the order because you can make orders from the backend and work on them as "drafts", thus not completed. 

The order state "flow" is as you say not a linear which could be interpreted by the design on the order states. This is noted for future improvements, thanks.

BR Rasmus Sanggaard
