### ISSUE TITLE
Misleading display of end date for price

### ISSUE THREAD

**Issue by dwlhs** [dynamicweb/DynamicWeb#112]
Hi :)

In the list of prices on a product, a missing end date is displayed as such:

![image](https://github.com/user-attachments/assets/997e1087-83ba-4874-9705-994e059a7fbd)

This confuses users, as they believe - in this case - that the to-date is before the end-date.

Could you add a different caption as "Never" or remove the value? Thanks :)

Br.
Lars

**Comment by nicped** [comment]
Price saves the wrong price to DB. 
https://dev.azure.com/dynamicwebsoftware/Dynamicweb/_workitems/edit/20509
