### ISSUE TITLE
SWIFT - feature request - google cookie complicance "EU User Consent Policy"

### ISSUE THREAD

**Issue by lhodynamicweb** [dynamicweb/DynamicWeb#113]
There is a new google privacy policy compliance, where a link to google's privacy policy is mandatory for consent-banners: 

Such as this:

![image](https://github.com/user-attachments/assets/258dbf61-2558-4d96-877e-f550ef2c1f5c)

Google’s [EU User Consent Policy](https://notifications.google.com/g/p/ANiao5poHT5giQ4UM4rW_0cF8UeIfMoJ3pTewA1CySQN2b2lyVp41rieIj-IDgZtJEcYTF-ksUTNmTDOjokM8xa8vl63Yljm59wOBEbQf8VJ4lz4TZb8p1YD0M_dO1_NTKnGKU_qd3WEbDoZW5eU6GvmSK4EB59xhUqo4btwxa8ZnW1AVKTTAmBooe-ile_xlfHa9iB55HXQhbKfbcKkBVBg4oPGrpEz1NQAqjAW7mW7x6IcaHGjh7lT) outlines your responsibility for making disclosures to, and obtaining consent from, end users of your sites and apps.

https://www.google.com/about/company/user-consent-policy-help/

**Comment by nicped** [comment]
Can you please point to where in the google  UCP it states that a link to the privacy policy have to be in the consent banner?

**Comment by lhodynamicweb** [comment]
![image](https://github.com/user-attachments/assets/9aba4354-170d-4fae-9e6a-dd9afa005acd)

https://www.google.com/about/company/user-consent-policy-help/

**Comment by nicped** [comment]
I got that one. But the Cookie banner links to the sites policy - and on the policy page is where you link to Googles policy - would that not suffice?
