### ISSUE TITLE
SWIFT - Feature request - UET Consent Enforcement for MAP Clients

### ISSUE THREAD

**Issue by lhodynamicweb** [dynamicweb/DynamicWeb#114]
Hi, 

There are new consent policies for MAP cliens, that SWIFT may need to adapt:

Important Update: UET Consent Enforcement for MAP Clients 
Dear MAP Clients,
We hope this email finds you well. We are writing to inform you about the upcoming enforcement changes regarding end user consent requirements for the Microsoft Advertising Platform (MAP).
To ensure continued compliance with applicable data protection laws and laws relating to the use of cookies and similar technologies, and the Microsoft Advertising terms and policies, we are updating the consent signal enforcement for end users on our platform.
We have been rolling out changes to handle all incoming requests from end users located within the European Economic Area. We plan to extend these changes to other regions, including but not limited to Switzerland and the United Kingdom, soon. Our Clients will need to convey end user consent status via the methods described below. This applies to your use of the Universal Event Tracking (UET) tag, which is a key component of MAP. If such information about end users’ consent status is not provided, MAP will not enable certain UET functionalities which may severely impact monetization and conversion tracking.
Moving forward aggregated KPI’s (conversions) shown in campaign UI may be estimated for all regions, starting with DE and NL. This change will provide a more robust insight for our Clients.
To prepare for the upcoming changes, we recommend that our Clients with traffic from the affected geographical areas take the following steps. Please note that this notice does not constitute legal advice, nor is it intended to address all legal or self-regulatory requirements that may apply to your organization.

 
Recommended Actions 
 
•	All Clients must ensure that they obtain end user consent through a consent management platform that complies with the IAB Transparency and Consent Framework (TCF) for all purposes that Microsoft Advertising (Vendor ID 1126) and Xandr Inc. (Vendor ID 32) engage in - as stated in the Global Vendor List [vendor-list.consensu.org/v3/vendor-list.json] for ad requests that are being sent to MAP. If TCF is not currently applied, we will also accept a binary consent signal.
•	Clients using UET must ensure to pass consent signals through designated URL parameters as outlined in our UET documentation.
•	UET documentation for consent mode & TCF:
•	https://help.ads.microsoft.com/apex/index/3/en/60119
•	https://help.ads.microsoft.com/#apex/ads/en/60186/2

**Comment by nicped** [comment]
Do Swift use UET?

**Comment by nicped** [comment]
This seems to be related to Bing maps which Swift does not use.
Swift supports Google Tag Manager and that can be used to configure many scripts and pass on consent appropriately. Swift handles the consent with GTM
