### ISSUE TITLE
"Product Groups with Invalid Characters" health check Update

### ISSUE THREAD

**Issue by nunoaguiar** [dynamicweb/DynamicWeb#115]
Consider **Monitoring > Health > Ecommerce data**

The check "**Product groups with invalid characters in Id**" does not check for a space in the Id (this was added by a bad data coming in from integration)

I understand the description says we should only use letters and numbers, but doing a quick visual check, seems to say everything is OK, when it is not.

Can that please be added? Or maybe a new check for spaces in IDs for product ids, fields, category fields and groups

Best Regards,
Nuno Aguiar

**Comment by nicped** [comment]
devops#20611
