### ISSUE TITLE
Dynamicweb provider as destination provider - interpret "Yes" / "No" as true false when inserting into a boolean field 

### ISSUE THREAD

**Issue by ivaigor96** [dynamicweb/DynamicWeb#117]
In BC when we are adding the custom fields, it's giving us an XML with "Yes" / "No" instead of true false
![image](https://github.com/user-attachments/assets/b63142f6-0a84-4cb1-81c3-47581cf286e6)

When importing into a field of type "Checkbox" for example "ProductActive" or a custom field - it does not work, the field value always remains false even if the value in source is "Yes"

We need either BC to give us "true" / "false" here or the DW provider should be able to figure out that this is a boolean

**Comment by DynamicRas** [comment]
Hi Igor,

What source provider are you using? Please describe the work flow of getting from your custom fields in BC to DW.

BR Rasmus Sanggaard

**Comment by ivaigor96** [comment]
@DynamicRas I am using the XML source provider and Dynamicweb provider as destination. We are getting XML using the "Import data with custom request add in". The fiels are part of the EcomProducts table of the GetEcomData request 
![image](https://github.com/user-attachments/assets/49d86ea8-14c2-4f46-a169-c6c9d0462534)

**Comment by DynamicRas** [comment]
Hi, 

Got it. We already have some logic that interprets the value when trying to map into a boolean field. We will add yes and no. 

BR Rasmus Sanggaard
