### ISSUE TITLE
Apply unit to stock overview

### ISSUE THREAD

**Issue by mortensnedker** [dynamicweb/DynamicWeb#118]
When reviewing product details, and from here have the view of "Prices & Stocks", you only have columns for _Stock location_ and _Amount_. It would be helpful to also have a column for unit specification (pc, package, pallet etc).

![image](https://github.com/user-attachments/assets/79cb3b8c-7679-46be-b6f8-39c9e4517b2f)

**Comment by nicped** [comment]
Got it - fixed on devops#20534
