### ISSUE TITLE
Click through to detail in Order Log

### ISSUE THREAD

**Issue by Justinvolved** [dynamicweb/DynamicWeb#119]
It would be good to be able to click through to a detail page of an Order Log line. Right now I can only hover, which doesn't work on mobile.

**Comment by DynamicRas** [comment]
Hi,

Just to make sure I understand you correct. You are talking about being able to see details in a better view then this right?
![image](https://github.com/user-attachments/assets/55223e76-4a04-482d-a12c-9b6dd5b73c15)

We are doing this in the integration log:
![image](https://github.com/user-attachments/assets/3b3b2bd2-33b2-4c05-a54a-9f6aab515c4f)

Not sure about the whole mobile scenario, but I see that a hover info box is not the best way of showing a lot of info. 

BR Rasmus Sanggaard

**Comment by Justinvolved** [comment]
Hey Rasmus,

Yes that is correct!
It would be great if the debug log could work that same as the integration. 
Altought I did also see in the eventlog you can just see a detail view without a modal. But that is up to you :-)

Thanks,
Justin

**Comment by DynamicRas** [comment]
Hi,

Got it. We'll improve the detail view. Thanks. 

BR Rasmus Sanggaard
