### ISSUE TITLE
Data integration job - copy table mapping

### ISSUE THREAD

**Issue by ivaigor96** [dynamicweb/DynamicWeb#120]
Some data integration setups, especially using conditionals, require adding the same table mapping and changing only a few values inside. Currently it's not possible to copy a table mapping, meaning that we have to go through the same process of selecting and adding the table mapping again, then updating all of the column mappings manually in the new table. Having a copy table mapping option would save a lot of time in these scenarios.
![image](https://github.com/user-attachments/assets/b356b945-9ca9-4b2c-91c4-b9289a7bdd44)

**Comment by DynamicRas** [comment]
Hi, 

Makes sense, we will add copy / duplicate table mapping which makes a 1-1 copy of the table mapping in the same job. 


BR Rasmus Sanggaard
