### ISSUE TITLE
Data integration jobs  conditionals - missing a greater than or equal, less than or equal operators

### ISSUE THREAD

**Issue by ivaigor96** [dynamicweb/DynamicWeb#121]
![image](https://github.com/user-attachments/assets/d5d1bc40-dce3-4329-b55f-81bd3a5733c1)

Not having these operators creates a need to do weird workarounds like substracting or adding to the original value to achieve the correct result. The scenario could be - date that is greater than or equal to today. Because we don't have the equal part, we then need to say date that is greater than today - 1 day.

**Comment by DynamicRas** [comment]
Hi,

Good point. We will add it. 

BR Rasmus Sanggaard
