### ISSUE TITLE
Optimize OData log sizes

### ISSUE THREAD

**Issue by nunoaguiar** [dynamicweb/DynamicWeb#123]
Hi,

We are running into an issue with Scheduled task logs for Odata integration activities filing up drive space.
These logs are duplicates of the data integration activity log for the job they are running. Each time it runs the log file continues to grow until the host server is out of disk space. It's not uncommon to have a single file with 1GB or more.
![image](https://github.com/user-attachments/assets/ece14780-c8be-408f-a23c-4ade4395d34e)

Would it be possible to have a toggle to disable logging on basic URL request scheduled task, or add a parameter to cap the log file size per task? 

We have considered adding some Powershell scripts on the VM itself to delete files/folders after they reach a certain size and/or some alerts monitoring disk space, but these feel like a patch; we would like to prevent the issue from happening in the first place.

As additional context, once the disk space is full, we start seeing some odd behaviors. Sometimes GlobalSettings get corrupted, sometimes we get a YSOD in the backend with some odd error. The issue is always a bit different. We've come to learn that when some really odd and/or new error shows up, it might be because of no disk space.

Original post in https://doc.dynamicweb.com/forum?PID=1605&ThreadID=93327 

Best Regards,
Nuno Aguiar

**Comment by DynamicRas** [comment]
Hi Nuno,

Yes it seems when you run the scheduled task via the URL activation it does accumulate more logs.

A fix could be to just activate the activity by using this URL instead:
![Screenshot 2024-08-06 at 11 07 50](https://github.com/user-attachments/assets/9a9e499f-fda5-49c6-b89d-4656167410b0)

Could this work for you? Or do you also need the scheduling part of the scheduled task?

BR Rasmus Sanggaard

**Comment by nunoaguiar** [comment]
Hi Rasmus

I'll ask Shawn and Jeremy about it. They should know better than I

**Comment by JeremyFesmire** [comment]
Hi Rasmus,

We do need the scheduling part of the scheduled tasks. The tasks creating the logs are for all of the batch endpoints on sites connected to BC which need to check for and bring over at least deltas on a regular interval.

-JF

**Comment by DynamicRas** [comment]
Hi,

OK got it. It is actually not OData log which is the problem then, but the actual scheduled task. We will take a look at it, in DW10 we have already changed it so it only keeps logs at certain time back. Bug #20621.

BR Rasmus Sanggaard

**Comment by DWDBE** [comment]
> Hi Rasmus,
> 
> We do need the scheduling part of the scheduled tasks. The tasks creating the logs are for all of the batch endpoints on sites connected to BC which need to check for and bring over at least deltas on a regular interval.
> 
> -JF

Hi Jeremy,
could you give more details about how the tasks are setup, what scheduled task add-ins do you use?
Or maybe share a solution url so we can look where the problems are.
BR, Dmitrij

**Comment by nunoaguiar** [comment]
Hi Dmitrij,

I can answer that:
- This one in particular is https://uat-ic.mydwsite1.com/
- The way (at least I see it being set up) is by right-clicking the Data Integration job and choosing "Schedule task"
![image](https://github.com/user-attachments/assets/d04ddada-49e8-448f-9ee3-99e4ce7a2586)

Best Regards,
Nuno Aguiar
