### ISSUE TITLE
Allow Relative File Path in AppSettings.Json for the FilesPath setting

### ISSUE THREAD

**Issue by joeyCV93** [dynamicweb/DynamicWeb#124]
**Is your feature request related to a problem? Please describe.**
We have had a problem where we are using a separate Swift Repo for our project, forked from https://github.com/dynamicweb/Swift. This is a problem as we have a configuration where each developer working on the project, will clone down both the DynamicWeb repo and the Swift repo to the same folder on their local machine, and should be able to just run the DynamicWeb solution and it pick up the correct Files directory of the Swift repo. This does not work as expected as the code in the DynamicWeb startup will not allow relative file paths, and instead when it detects that the path is relative, will append the root of the DynamicWeb repository to it. This means that it cannot detect the correct path of the Swift repo as it is outside the root of the DynamicWeb repo.

This is the appSettings,Json value i am referring to:

`"FilesPath": "DynamicWebSwift\\Swift\\Files"`

Our Folder structure of the checked-out repos is:

```
<Their Base Folder for Git repos>/DynamicWebSwift/Swift/Files
<Their Base Folder for Git repos>/DynamicWeb
```

**Describe the solution you'd like**
It would be good to update the following method:
`builder.Services.AddDynamicweb(builder.Environment, builder.Configuration);`
to also take in a boolean of `useRelativeFilesPath` that will allow the swift repo to be used without working around or copying it into the DynamicWeb rep folder.

If an absolute path is required inside this method, it should work out what the absolute path of the given relative path from the "FilesPath" appSettings value from the Hard drive root rather than assuming it will be inside the DynamicWeb repo folder.

**Describe alternatives you've considered**
We have two options to work around this and neither are ideal:

1. Each developer must change appSettings.json FilesPath variable to be their full path they have checked out the code to:

E.g `C:\Users\<USERNAME>\<Their Base Folder for Git repos>\DynamicWebSwift\Swift\Files`

This is extra work for each developer and not something that certain front-end developers may want to do. It also is prone to someone accidentally checking this in, as we cannot exclude appSettings.json from the repo using .gitignore.

2. Extra Code in Program.cs that will overwrite the Variable once it has been loaded into memory, and before `builder.Services.AddDynamicWeb()` has executed. This needs to programatically convert the relative path to a absolute path.

We have implemented this approach, but it is not a clean or ideal solution, and is something that we shouldn't have to do at all really.

```
var builder = WebApplication.CreateBuilder(args);
OverrideSwiftFilesDirectory(builder);
builder.Services.AddDynamicweb(builder.Environment, builder.Configuration);

//...

void OverrideSwiftFilesDirectory(WebApplicationBuilder webApplicationBuilder)
{
    var directoryInfo = new DirectoryInfo(Environment.CurrentDirectory);
    var appSettingsPath = webApplicationBuilder.Configuration.GetValue<string>("FilesPath");
    var projectsRoot = directoryInfo.Parent?.Parent?.ToString();
    if (!string.IsNullOrEmpty(appSettingsPath) && !string.IsNullOrEmpty(projectsRoot))
    {
        webApplicationBuilder.Configuration["FilesPath"] = Path.Combine(projectsRoot, appSettingsPath);
    }
}
```

**Additional context**
The Source of the issue is this line:

`filesPath = flag ? (Path.IsPathRooted(filesPath) ? filesPath : Path.Combine(environment.ContentRootPath, filesPath)) : Path.Combine(str, "Files");` 

Which is in 
`DynamicwebApplicationExtensions.AddDynamicweb() Line:72`
`Microsoft.AspNetCore.Builder.DynamicwebApplicationExtensions.AddFileProviders() Line:149`

**Comment by nicped** [comment]
Can you use environment variables?:
[https://doc.dynamicweb.dev/documentation/fundamentals/setup/installation/environments.html](https://doc.dynamicweb.dev/documentation/fundamentals/setup/installation/environments.html)

Adding the FilesPath to your appsettings.json should solve this issue.

**Comment by dw-jea** [comment]
Hi joeyCV93,

DynamicWeb 10 does support relative paths, [see here](https://doc.dynamicweb.dev/documentation/fundamentals/setup/installation/environments.html#environment-variables). In DW10, the root path is the application/host folder. This is the folder you move relatively to, unless your path is absolute. You can move up the folder structure by using double dots.

If your application is located at `<git folder>\DynamicWeb` and Swift is located at `<git folder>\DynamicWebSwift\Swift\Files`, you can simply put `..\\` in front of your `FilesPath`. Your `appsettings.json` would look like this:

```json
{
    "FilesPath": "..\\DynamicWebSwift\\Swift\\Files"
}
```

If you need to move further up, you can chain as many double dots as the folder structure will allow. At start-up, DynamicWeb will resolve the path to an absolute path and use that for the lifetime of the application. You can see the calculated absolute path to the files folder when DynamicWeb starts up. See the output log from Kestrel in the terminal. If you're using IIS, you need to enable logging output in you `Web.config` to see it.

**Comment by joeyCV93** [comment]
@dw-jea Please see the extra context in the new issue i have created.

https://github.com/dynamicweb/DynamicWeb/issues/158
