### ISSUE TITLE
Show completed state of a scheduled task

### ISSUE THREAD

**Issue by lbw-dynamicweb** [dynamicweb/DynamicWeb#125]
In the list of Scheduled Task it is not possible to add a column with the state of the last run - so I have no easy overview if any of the tasks have failed.
![image](https://github.com/user-attachments/assets/6e2a0a9a-6f37-49e2-b437-acf474cfb402)

**Comment by DynamicRas** [comment]
Hi,

We can certainly add that information to the list. We are also considering saving the information on the last runs with links to the corresponding logs to show on the overview of each schedule task.

BR Rasmus Sanggaard
