### ISSUE TITLE
Jumping repositories interface

### ISSUE THREAD

**Issue by dwlhs** [dynamicweb/DynamicWeb#127]
Hi :)

Working in the repository interface can cause some dizzyness, because it refreshes the page every two seconds or so. If e.g. we're scrolling down to the review or manage the Builds, when the page refreshes, it jumps back to the top, because the progress of the instance build needs to be updated - even when it's not running.

Could the new funky progress bare in the top on DW 10 be used for that instead? Otherwise, would it be worth considering whether the progress indicator is necessary, could be switched on/off, or could be triggered manually.

Br.
Lars

**Comment by nicped** [comment]
Yes. We have also made other changes to that screen for 10.7. Will fix the flickering as well.
