### ISSUE TITLE
Improved error handling on uninteded usage of index builder

### ISSUE THREAD

**Issue by dwlhs** [dynamicweb/DynamicWeb#128]
Hi :)

A colleague reached out after a rather traumatizing experience in Repositories. Updating an instance of a product index resulted in the following error message:

![image](https://github.com/user-attachments/assets/92872141-90b2-4d55-a892-a99ca275405b)

In Insights, the stack trace contained the following:

2024-08-13 10:49:24.9079: Product index builder experienced a fatal error.. System.ArgumentNullException: Value cannot be null. (Parameter 'values')
   at System.String.**Join**(String separator, IEnumerable`1 values)
   at Dynamicweb.Ecommerce.Indexing.ProductIndexBuilder.LoadPrimaryDetailImages(SqlConnection connection, Tracker tracker)
   at Dynamicweb.Ecommerce.Indexing.ProductIndexBuilder.Build(IIndexWriter writer, Tracker tracker)

A glance into the source code revealed that the join method receives a ProductIDs collection parameter, which in this case is Null:

![image](https://github.com/user-attachments/assets/24cb99f8-fda6-4982-93e3-3398b511aadc)

The builder was set to use UpdateWithIds which the documentation states is intended for automated update where a collection of id's is passed, but cannot be called manually:

![image](https://github.com/user-attachments/assets/66d17750-a309-4d63-9948-bdc7fb3b33d0)

So, the question is, could this situation avoided or handled more gracefully? 

- Could the update button be removed or deactived for this type of build?
- Could a null check be incorporated in the code?
- Could the error message be less frightening?
- Could the error message perhaps instruct the user, what they did wrong?

Just want to add that the instance files were unaffected, so the error message could be removed by deleting the log file in the Diagnostics folder. But it did cause a bit of panic just before a go-live :)

Br.
Lars

**Comment by nicped** [comment]
I have added bug on the null check and a feature request to change the SQL to use commandbuilder and another to disable the build button if it does nothing.

**Comment by dwlhs** [comment]
Fantastic :)
