### ISSUE TITLE
Custom error page in DW10

### ISSUE THREAD

**Issue by carodeweze** [dynamicweb/DynamicWeb#129]
You can't add a custom 404 page and the automatically generated page lacks navigation and brand consistency.

It would be nice if DW10 supports a custom error page and that you can link it like with DW9:
<img width="1235" alt="Screenshot 2024-08-13 at 11 26 47" src="https://github.com/user-attachments/assets/e31fc368-adfa-4001-a800-8cbc242e5b22">

**Comment by nicped** [comment]
You can setup custom 404 pages on websites:

![image](https://github.com/user-attachments/assets/60a97f92-7ced-4fd7-978a-cac3bc2b909d)

The 404 is depending on the hostnames attached to a website, so the general setting have been removed and you can only set it on the website.
