### ISSUE TITLE
All variant product numbers indexed in the master product

### ISSUE THREAD

**Issue by nunoaguiar** [dynamicweb/DynamicWeb#13]
Hi

9 out of 10 customizations we do related to IndexBuilderExtenders is adding the product numbers of a variant to the master product, so that whenever users search for any variant product number (aka SKU), they find that record.

Since we do it that often, it would probably be a good feature to add to the system.

I would envision a new auto-generated index field (only on master records) that we could then create an expression for search.

Best Regards
Nuno

**Comment by nicped** [comment]
Added to DW10 now.
