### ISSUE TITLE
Swift translations: can't read long translation keys from list view

### ISSUE THREAD

**Issue by ivaigor96** [dynamicweb/DynamicWeb#133]
Example of long translation keys 

![image](https://github.com/user-attachments/assets/f6161dcd-7d79-410c-bd2b-0e6853957df1)

![image](https://github.com/user-attachments/assets/0b294cea-b0a2-4b8b-a6ad-41e415aaa335)

In the view it's not possible to see the full value of the Name column, it's too short
When you hover over the name - full value is not shown
The manage columns is missing the option to remove all columns except the "Name"

![image](https://github.com/user-attachments/assets/edcb760f-555e-4748-85c9-3862f0da7d34)

![image](https://github.com/user-attachments/assets/cf7fa5cf-4b46-429f-8efc-758f8b39c3f2)

It only has 2 columns, but in the view there is a column per language 
![image](https://github.com/user-attachments/assets/b7e6e99a-1864-4c6d-ac62-9b4285d54f67)

We need an easy way to read longer translation keys in this list view, having to click edit to check what value it is is hard

**Comment by nicped** [comment]
We are currently working on a feature to resize columns in lists.
