### ISSUE TITLE
Switching language while on product details page shows blank page if product is not active in the new language

### ISSUE THREAD

**Issue by ivaigor96** [dynamicweb/DynamicWeb#134]
Example:
A product exists in Swedish, but not in English
If you change the website language from Swedish to English while on the product details page of said product - it will try to open the product details page of the same product in English. If the product is not active in English it will not show a 404 it will show a page with only the header and footer - the entire content area will be blank.

![image](https://github.com/user-attachments/assets/07589778-1cb2-4f30-af1a-fef5b42046d1)

We need some sort of handling in this scenario, either a 404 or a redirect or something to indicate to the user what went wrong

**Comment by nicped** [comment]
Also in devops as bug/investigation. Closing here.
