### ISSUE TITLE
Grid Edit Fix different column 

### ISSUE THREAD

**Issue by RosaHarrisBD** [dynamicweb/DynamicWeb#136]
Hi, 

With using the grid edit function, only column number stays fixed on its place when you scroll with the horizontal bar. It would be very nice if via the interface you can appoint which column you want to be fixed, because the number is often times not very indicating for the attributed data changes that the user want to apply. E.g, the name would be more helping. 

Kind regards, 

Rosa Harris

**Comment by nicped** [comment]
Hi Rosa

Thank you for the request. This feature is already being implemented and you can expect the first version of it to show up in 10.8 with improvements in the coming releases.

BR Nicolai
