### ISSUE TITLE
All users screen

### ISSUE THREAD

**Issue by ivaigor96** [dynamicweb/DynamicWeb#14]
The users area in DW10
![image](https://github.com/dynamicweb/DynamicWeb/assets/21162540/29e41abc-8371-4691-b952-7ed424e34ae5)

Current problems:

- Can't search all users, need to first know which user group the user is part of
- When importing a user from integration, if the user is not assigned to at least 1 group - impossible to find the user in the interface

**Comment by ArtjomJensen** [comment]
I came here to write the same thing. 👍

**Comment by dwlhs** [comment]
+1

**Comment by nicped** [comment]
Closed with https://dev.azure.com/dynamicwebsoftware/Dynamicweb/_workitems/edit/20143
Eta: 10.7
![image](https://github.com/user-attachments/assets/6dee6748-1977-464e-8b19-93a2a339aee3)
