### ISSUE TITLE
Better breadcrumb navigation on the edit product screen

### ISSUE THREAD

**Issue by ivaigor96** [dynamicweb/DynamicWeb#140]
Tested on DW 10.6.11

When opening edit product the navigation looks like this

![image](https://github.com/user-attachments/assets/6b79818a-53fb-460b-8f1b-501fb1286f1d)

However, when entering related products or prices or something similar the navigation looks like this

![image](https://github.com/user-attachments/assets/a610edc9-c0f8-4655-af6c-515b2c6a3b1f)

I think it should be Products > Channels > All products > ESSTACK NORDIC PRO > Related Products

So like this
Products > Channels > All products > [Product name] > [Sub page]

Currently if you enter an edit price or product relation and then click back in the browser - it will go back to the edit screen of the price or relation not the product. You have to click back many times to get back to the edit product screen again

**Comment by nicped** [comment]
Yes - we are struggling with making these breadcrumbs behave correctly together with back buttons etc.
We are working on improving this.
