### ISSUE TITLE
Scheduled Tasks subtask naming

### ISSUE THREAD

**Issue by dwlhs** [dynamicweb/DynamicWeb#142]
Hi :)

When setting up subtasks, then adapt the naming of the add-in or activity. It would be very useful, if we could populate the TaskName and have the names reflected in the list to add more context to the sequence of tasks:

![image](https://github.com/user-attachments/assets/bd218b79-5512-41f3-bbc7-1b85940cc7d1)

Thanks :)

Br.
Lars

**Comment by DynamicRas** [comment]
Hi, 

We already have comment field, which I think solves the need:
![image](https://github.com/user-attachments/assets/e3c4ec6b-4b76-4537-85cb-972974507b0f)

BR Rasmus Sanggaard

**Comment by dwlhs** [comment]
Thanks, I've been looking at 10.6, where this is not present. Agree, the comment field is exactly what is needed :)

Br.
Lars
