### ISSUE TITLE
Directly translate product information when creating a new language version

### ISSUE THREAD

**Issue by Justinvolved** [dynamicweb/DynamicWeb#143]
If I want to add a new Language version of a product, and use a translation service like Deepl to translate it from a source language, I have to perform 2 seperate steps in the UI. 
It would be great if an option could be added to the "Manage Language" panel, so that I can choose to immediately translate the data from a certain language:
![image](https://github.com/user-attachments/assets/6ce3436e-45ba-4cc8-aa82-4fe4bbea2e2b)

**Comment by nicped** [comment]
We are currently working on changing the workflow around languages and translations. So this particular window will change in a release not to far away. This particular situation has been discussed - so when you do translate for a product that is not in a language, the language will be created as part of that.
