### ISSUE TITLE
Add grouping and sorting of "Group Fields"

### ISSUE THREAD

**Issue by kasperlegarth** [dynamicweb/DynamicWeb#144]
Group fields do not render in the sort order they are labelled within the database. I would assume that is just the order they have been created. 

![Skærmbillede 2024-09-18 111808](https://github.com/user-attachments/assets/11c49fbd-2fe5-475f-914c-65d7b59c8cd5)

I want to request the possibility of sorting the group fields. So that if you make a field related to another field you can put it next to it. 

Futher more i would like to request the possibility to group fields together to get a view like the rest of the UI, where you can collapse groups etc.

Kind regards
Kasper

**Comment by nicped** [comment]
This is a missing feature for these fields. We will add sorting of the fields and let it apply in editing interface. Devops#21204

Also note that we are currently rolling out a feature called "Screen presets" (name might change) where you can define exactly what tabs and sections you want on product edit and you can also control where fields will be and in which order. Then you can use these screen presets in e.g. workflows.
