### ISSUE TITLE
Enable Multiple values in Quick search in PIM

### ISSUE THREAD

**Issue by CapiauD** [dynamicweb/DynamicWeb#147]
The Quick Search in PIM should be able to handle multiple values, seperated by a comma

Prompt:
![image](https://github.com/user-attachments/assets/b887a4b1-cf6a-4323-80f6-91d6255dcf8e)

Result:
![image](https://github.com/user-attachments/assets/c2b121dc-3497-4a47-ba8d-2f640b279c05)

**Comment by nicped** [comment]
This task has been created as devops#21242 and scheduled for Q4.

**Comment by SoJensen** [comment]
Hi,

Using quick search in PIM with multi values, are only working within a query-result, so not below node "All products" and in Channel structures.

So if needed to use on all available products, you need to make a Query, there show all products.

/Søren
