### ISSUE TITLE
Extranet - password recovery page - include values from the user in the email

### ISSUE THREAD

**Issue by ivaigor96** [dynamicweb/DynamicWeb#148]
When setting up password recovery email on the extranet app it’s possible to chose either template or page. When selecting page
 
![image](https://github.com/user-attachments/assets/7853621d-3a5a-47ab-b03d-ece0d53be2ae)

![image](https://github.com/user-attachments/assets/bbaeff50-e46c-4b6b-b8f1-c7eaf6b34839)

The page has some values contained inside {{}}, these values are taken from the user when using for example – the email area in DW10 to send out a newsletter
However, the extranet app is not replacing the values in the email with the values from the user
It would be great if this behavior of taking values from the user when sending an email would work also for the extranet

**Comment by nicped** [comment]
Added in devops#21238, out with 10.8

We are currently in the process of creating new user management modules for e.g. password recovery emails using viewmodels. So this feature will soon expire, but we added all user tags to the email.
