### ISSUE TITLE
Also copy conditionals when copying mappings in an integration job

### ISSUE THREAD

**Issue by CapiauD** [dynamicweb/DynamicWeb#149]
Hi team,

When copying a table mapping via the UI within an integration job, the conditionals are not copied. It would be better if it included the conditionals or that you have the option to.

![image](https://github.com/user-attachments/assets/deda77ae-d234-4f02-a985-b12844d8bf6d)

![image](https://github.com/user-attachments/assets/4edbd674-1082-400e-8da0-a8d2e89a1b98)

![image](https://github.com/user-attachments/assets/65b19d79-5bf1-4526-937c-a036ede2bc0b)

**Comment by DynamicRas** [comment]
Hi,

I see your point. I have added it to our backlog. Thanks.
BR Rasmus Sanggaard
