### ISSUE TITLE
Admin UI navigation: "Open link in new tab" opens the same page again and not the actual page

### ISSUE THREAD

**Issue by ivaigor96** [dynamicweb/DynamicWeb#15]
![image](https://github.com/dynamicweb/DynamicWeb/assets/21162540/9184288a-8454-4fa8-b921-905f82d10e48)

Today there are cases where having multiple different windows and comparing them side by side can be needed. Clicking open link in new tab on a different area than you are on now, for example being on the content area and clicking open new tab (or mouse clicking) on settings, will always open the content - not the settings, or any other screen. This means that if you want to have 2 different tabs quickly you need to dupplicate your current tab and only then switch to a new one.

**Comment by nicped** [comment]
This has been fixed - maybe in 10.6, but at least in 10.7
