### ISSUE TITLE
Filtering on multiple fields in grid-edit DW9 PIM

### ISSUE THREAD

**Issue by barendmosch** [dynamicweb/DynamicWeb#151]
Hi there!

In the PIM grid edit on DW 9 its possible to filter on fields, for instance: only get certain states or workflows. But is it possible to filter on multiple fields at once. i.e.: Get all products and then filter on Workflow=21 and state=1.

At the moment adding a second filter removes the first one.

Example screenshots
Filter on EAN:
![image](https://github.com/user-attachments/assets/5e946bd4-8f7e-4862-91cf-d22d1ce8b79b)

After adding a filter on name it removes the filter on EAN:
![image](https://github.com/user-attachments/assets/80e5c757-9f3b-4c3c-bbb6-2c42459ffe81)

The feature request would be: Adding multiple filters instead of the 1 restriction.

Kind regards,

Barend Mosch, Bluedesk

**Comment by nicped** [comment]
Thank you for the request. This feature is partially implemented in DW10 where filtering is working somewhat different than DW9. New features of this size will only be added to Dynamicweb 10.
