### ISSUE TITLE
User edit: details - show custom field values

### ISSUE THREAD

**Issue by ivaigor96** [dynamicweb/DynamicWeb#153]
Currently the custom field values are only visible when clicking edit on a user, they are not available in the overview
It would save 2 clicks to have

![image](https://github.com/user-attachments/assets/05199696-6890-4575-a2ac-d8969dee8145)

Currently to access custom user fields the only way is to:

Open user details screen
Click edit
Switch to fields tab to see only the custom fields

After this change:

Open user screen
Switch to details tab and see all field values in a single screen

The details tab is useful for seeing all of the information in a single view, since the edit mode splits everything into tabs
Being able to click edit and go directly to fields would also be useful

**Comment by nicped** [comment]
Good one!
Added to the Q4 backlog, devops#21334
