### ISSUE TITLE
Hawaii Time Zone on Date timestamps

### ISSUE THREAD

**Issue by nunoaguiar** [dynamicweb/DynamicWeb#174]
**Is your feature request related to a problem? Please describe.**
Customers naturally want to use their preferred time zone (usually where they are located), but we have difficulty ensuring that across the board.
In Azure Cloud, the SQL Server has to be UTC, but the VM can be whatever time zone we want.

**Describe the solution you'd like**
We'd like for the data in the DB to be UTC and the API/ViewModels to expose it in the Server's time zone accurately (and/or in UTC as well), so that can get it more accurately in both the webapi's and templates

**Describe alternatives you've considered**

- We considered customizing templates to show the user's desired time zone - but that makes it harder to relate with the backend on lists, auditing and logs
- We tend to hide the time (only show date), but depending on when something happens (i.e. order placed), it shows up as "the next day" for the user, which is confusing
- We also end up appending "GMT" to every date, but it's not something some users relate to.

**Additional context**
This topic was discussed with Jeppe at the Summit

**Comment by nicped** [comment]
Task is too big an risky...

**Comment by nunoaguiar** [comment]
@nicped I understand and we will see how we can find viable alternatives to our customers and partners.

I would expect this could this be a (no sooner than) DW11 feature, or something that, as new Date and DateTime fields and properties are added into the system, starts to be a consideration, making this a smaller issue (rather than a larger one) moving forward.

If this can be kept "in the back of your mind" we would appreciate it.
