### ISSUE TITLE
Product selector: products where ProductActive is False are not shown

### ISSUE THREAD

**Issue by ivaigor96** [dynamicweb/DynamicWeb#18]
When a prduct is set to inactive - it is not being shown in the product selector

This is a major problem when there is a process where an inactive product is first added to a pargraph for example, and later becomes active (after enrichment or activated from integration). If this restriction is forced, the product active field is then a system field in a way, because it's main purpose at the moment is front end, but after this change, it also has consequences on the back end interface. We then need to tell all customers to only use this field when you don't want to see the product again in the product selector, and setup a different field in the product query for front end visibility, or use product publicaiton.

I will just address some of the possible critisim I already see now:
1. Just use "Show in product list" for front end visibility and not product active. If we have to do it like this from now on then we need to be very clear about what else does the field "product active" do. I know that it can be used for limiting indexing for instance and now it seems to be also affecting the product selector. But in all my years of projects, we always use the product active fields for front end purposes only, and "show in product list" is ignored. We need a good reason to have an extra layer of activeness for a product just for the back end that would be separate from the front end. 
2. Just use publication on the product. Publication is more complicated to setup from import than a single boolean value. When a customer ticks a checkbox in the ERP system we just get the new true / false value. Publication in most cases is not necessary and is overkill

 In my view, we really either need a toggle or a setting to show the inactive products in the product selector, or at least it has to be somehow more clear that such restrictions exist because it can be extremely confusing to see the product in the products area in a group and then in the same exact group in the content area not see the product without an explanation.

**Comment by nicped** [comment]
Closed with https://dev.azure.com/dynamicwebsoftware/Dynamicweb/_workitems/edit/19357/
