### ISSUE TITLE
Option to disable/enable sceduled task easy

### ISSUE THREAD

**Issue by lbw-dynamicweb** [dynamicweb/DynamicWeb#183]
In the scheduled task overview list, is it not possible to disable a task by pressing the "Activated" button. Nor is it possible to enable/disable the task in the menu. You'll have to edit it, and the edit the general settings to activate/deactivate it.

![image](https://github.com/user-attachments/assets/a41dc8b8-a754-4511-97ff-e12e68eb48dc)

**Comment by DynamicRas** [comment]
It is possible to do it from the menu the page just does not refresh. We will fix it. 

BR Rasmus Sanggaard
