### ISSUE TITLE
User Provider sending mail before the user is created

### ISSUE THREAD

**Issue by lbw-dynamicweb** [dynamicweb/DynamicWeb#184]
When importing a large number of users through the User Provider, and with the destination configured to send emails to new users, emails are triggered before the users are fully created in the system.

This causes issues if the import process fails at a later stage or if we’re importing a large volume, such as 2,000 users. In this scenario, the email-sending process can take a very long time, leading users who try to access the link in their email to encounter a "User not found" error.

**Comment by DynamicRas** [comment]
Hi,

Thnx, I have added to our backlog for next sprint.

BR Rasmus Sanggaard
