### ISSUE TITLE
Integration: Send request always adds $metadata

### ISSUE THREAD

**Issue by lbw-dynamicweb** [dynamicweb/DynamicWeb#186]
Using the Send Request
![image](https://github.com/user-attachments/assets/24cdaf65-1bb0-4573-837a-433dff1d564c)

does not send the string in the editable URL, but only the fixed URL with added $metadata

![image](https://github.com/user-attachments/assets/a67e8b70-bc66-40de-83ea-2fde6f8ef88f)

**Comment by dwlhs** [comment]
+1

**Comment by lbw-dynamicweb** [comment]
Same as https://github.com/dynamicweb/DynamicWeb/issues/188
