### ISSUE TITLE
Clear all cache

### ISSUE THREAD

**Issue by ivaigor96** [dynamicweb/DynamicWeb#19]
During development or debugging it would be very helpfull to clear all cache at once somehow

**Comment by nicped** [comment]
I believe you can do this under settings and the list of services:

![image](https://github.com/dynamicweb/DynamicWeb/assets/3715307/688c9810-0493-4a4b-92b4-ffaef55d0af1)

Is that sufficient?

**Comment by ivaigor96** [comment]
> I believe you can do this under settings and the list of services:
> 
> ![image](https://private-user-images.githubusercontent.com/3715307/323655563-688c9810-0493-4a4b-92b4-ffaef55d0af1.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MTM1MTMyMjksIm5iZiI6MTcxMzUxMjkyOSwicGF0aCI6Ii8zNzE1MzA3LzMyMzY1NTU2My02ODhjOTgxMC0wNDkzLTRhNGItOTJiNC1mZmFlZjU1ZDBhZjEucG5nP1gtQW16LUFsZ29yaXRobT1BV1M0LUhNQUMtU0hBMjU2JlgtQW16LUNyZWRlbnRpYWw9QUtJQVZDT0RZTFNBNTNQUUs0WkElMkYyMDI0MDQxOSUyRnVzLWVhc3QtMSUyRnMzJTJGYXdzNF9yZXF1ZXN0JlgtQW16LURhdGU9MjAyNDA0MTlUMDc0ODQ5WiZYLUFtei1FeHBpcmVzPTMwMCZYLUFtei1TaWduYXR1cmU9MWZjY2NjYzRmZTY1M2RjYWExOTk4ODBhYjViMTgwMmE3ZTVlNGRmNzY2OTBjODU2MTg0MTg1OTgyZTlhOGJmZiZYLUFtei1TaWduZWRIZWFkZXJzPWhvc3QmYWN0b3JfaWQ9MCZrZXlfaWQ9MCZyZXBvX2lkPTAifQ.NBPYqUboXJQbI96ufIIEeM3M8Y1bPVx4sEGEQHPzvwY)
> 
> Is that sufficient?

Yes, this should be sufficient
