### ISSUE TITLE
Improvements to Scheduled Tasks

### ISSUE THREAD

**Issue by dwlhs** [dynamicweb/DynamicWeb#195]
Hi :)

A collection of improvements to the scheduled tasks feature we have gathered.

- Currently, there is only one queue, and only one task can run at a time. We have scenarios, where large synchronizations, e.g., product information, run for hours, but small tasks scheduled to run more frequently, e.g., sending orders to ERP, are waiting until the large job is finished. It would be nice if we could configure different queues, so one queue is reserved for longer running jobs, another queue is reserved for running smaller integration, and even a third queue reserved for running system tasks. We should have the ability to select the queue on the configuration of the scheduled task.
- Schedule tasks to run within different timespans, so jobs run in intervals of 15 minutes, but only within or outside business hours.
- Visualization of the queues, so we can see which tasks are scheduled to run and in which order
- Manage the que, so we may cancel an activity like in a printer queue or move it up and down in priority.
- Possibility to cancel a job while it is running

Thanks :)

Br.
Lars

**Comment by lhodynamicweb** [comment]
Yes, also very relevant for dw9 customers

**Comment by nunoaguiar** [comment]
Hi,

Maybe it goes without saying, but the visualization of what's running vs the "warning" icon (as we have it in DW9) is important. It's not obvious of what's running and that it's running. Sometimes some of the tasks (subtasks in DW10) take considerably longer (specially when importing large sets of OData), and it's not easy to tell what's running.

Nuno

**Comment by DynamicRas** [comment]
Hi, 

Thanks for the recap. As this is quite a big wish list it is going to be part of a coming roadmap. 

BR Rasmus Sanggaard

**Comment by Wassini** [comment]
Hi. Is there a link to this scheduled task /queue roadmap?

**Comment by DynamicRas** [comment]
Hi,

This feature request is quite broad, as it contains multiple requests in one without any prioritization. However, we have a remake of scheduled tasks on our Discovery roadmap, meaning we are currently exploring the needs and possibilities. It is likely that this will be developed in some form in the future.

BR,
Rasmus Sanggaard
