### ISSUE TITLE
Angel user to see all dashboards

### ISSUE THREAD

**Issue by A-Kold** [dynamicweb/DynamicWeb#197]
**Is your feature request related to a problem? Please describe.**
When using Angel login, it's important for us to be able to see dashboards made by ourselves, or by other users to assist. At the moment, Angel users cannot view any dashboards, which means that we are unable to see its content, and thereby also use the dashboard to be directed to the query. This means we would need to create a test user separately, and then go around to every possible dashboard manually adding that user just to view the dashboard.

Switching between an Angel user and a test user repeatedly to access and check dashboards is a tedious task. This adds unnecessary complexity to a process that should be straightforward, making the workflow inefficient. This is both the case on new solutions, and if we need to assist on live sites. It should be expected that Angel users can view dashboards in order to perform our functions. The current restriction also contradicts the purpose of an Angel user’s role. 

**Describe the solution you'd like**
Make all dashboards visible to Angel (or angel+admin) users.

**Describe alternatives you've considered**
Following might be an attempt to make it work, but it seems like the check has no effect.
![image](https://github.com/user-attachments/assets/261a645d-7b28-4757-969a-44bdc4817fb1)

**Comment by nicped** [comment]
Mail to has been send on topic.
