### ISSUE TITLE
Discount properties: show only channels of type Shop

### ISSUE THREAD

**Issue by mortensnedker** [dynamicweb/DynamicWeb#198]
When setting up a discount and selecting a Shop for which the discount applies, please reduce the dropdown list to only channels of type 'Shop':

![discount](https://github.com/user-attachments/assets/0f54c91e-555e-46a0-ab7c-00484f7f43ab)

**Comment by nicped** [comment]
It could also be a channel used externally that should have the discount. We would like not to limit when and how it can be used as it might just lock options to do what you want....
