### ISSUE TITLE
Prevent anonymous requests in Live Integration

### ISSUE THREAD

**Issue by lbw-dynamicweb** [dynamicweb/DynamicWeb#201]
Using the Live Integration, it is possible to disable requests for anonymous users in the setting, but this still requests prices and stock for logged in users without a Customer Number. It seems that Live Integration substitutes the blank customer number with the text "Anonymous".

I would like to have an option to disable requests when the user does not have a customer number filled.

**Comment by DynamicRas** [comment]
Hi, 

There is a setting on a user edit screen called: _Disable live prices_, it can be activated for the users with empty customer number but it will need a manual intervention (or run an update sql script).

This has been the behavior for ages and we are not looking into added more setting to the current live integration.

BR Rasmus Sanggaard
