### ISSUE TITLE
Firehose: SELECT COUNT

### ISSUE THREAD

**Issue by lbw-dynamicweb** [dynamicweb/DynamicWeb#209]
This is a minor change request:

Using the SQL statement:
SELECT COUNT(*) FROM EcomProducts
causes an error

Instead we must add a column name to the statement:
SELECT COUNT(*) **as Counter** FROM EcomProducts

This causes confusion when quickly trying to use the default/easy way of getting a count, so would it be possible to support the COUNT without adding the column ?

**Comment by nicped** [comment]
devops#22524
