### ISSUE TITLE
Ability to set time on Price valid to and from

### ISSUE THREAD

**Issue by VincentTwoday** [dynamicweb/DynamicWeb#21]
Hello! It would be nice to have the ability to set the time as well as the date when updating prices via the administration:

![image](https://github.com/dynamicweb/DynamicWeb/assets/167538812/f10882ea-8435-4139-a226-ff1526372b4b)

**Comment by DynamicRas** [comment]
Hi Vincent,

Noted. FYI, we have both time and date on DW10.

BR Rasmus Sanggaard

**Comment by nicped** [comment]
Will not be changed on DW9
