### ISSUE TITLE
Insufficient log information in live integration

### ISSUE THREAD

**Issue by dwlhs** [dynamicweb/DynamicWeb#22]
I received an error trying to create an order in BC via DW10 live integration. The request failed, but the log in Dynamicweb wasn't very helpful:

04/22/2024 09:03:18.082 am: ConnectionError: An error occurred while calling CalculateOrder (ID: ORDER701, CreateOrder: True) from Web Service: 'Response status code does not indicate success: 500 (Internal Server Error).'.
04/22/2024 09:03:18.084 am: ConnectionError: Error CalculateOrder Order Id:'ORDER701' CreateOrder:'True' Message:'Response status code does not indicate success: 500 (Internal Server Error).'.
04/22/2024 09:03:18.088 am: Error: Order with ID 'ORDER701' was not created in the ERP system.

I tried submitting the same order via Postman and received a much better response message:

```
<s:Envelope xmlns:s="http://schemas.xmlsoap.org/soap/envelope/">
    <s:Body>
        <s:Fault>
            <faultcode xmlns:a="urn:microsoft-dynamics-schemas/error">a:Microsoft.Dynamics.Nav.Types.NavTestFieldException</faultcode>
            <faultstring xml:lang="en-US">Blocked must be equal to 'No'  in Item: No.=10016. Current value is 'Yes'.</faultstring>
            <detail>
                <string xmlns="http://schemas.microsoft.com/2003/10/Serialization/">**Blocked must be equal to 'No'  in Item: No.=10016. Current value is 'Yes'.**</string>
            </detail>
        </s:Fault>
    </s:Body>
</s:Envelope>
```

In earlier versions, we would be able to see this message in the live integration log. We need this information in the log, so we don't have to use third party tools to debug.

**Comment by DynamicRas** [comment]
Seems to be some missing logging. I have added the task to the sprint.
