### ISSUE TITLE
SingleSelect Listboxes auto-set first option

### ISSUE THREAD

**Issue by KrisKrus** [dynamicweb/DynamicWeb#26]
**Is your feature request related to a problem? Please describe.**
In Grid edit on DW9 the single select auto sets the first options by default, this should not be the case.
Same problem has been reported in DW10

**Describe the solution you'd like**
I don't want it to auto-select unverified data. 

**Describe alternatives you've considered**
Set "Nothing selected" instead (by default)

**Comment by nicped** [comment]
This has been fixed
