### ISSUE TITLE
Monitoring Health for invalid group Ids

### ISSUE THREAD

**Issue by nunoaguiar** [dynamicweb/DynamicWeb#30]
When integrating ecommerce data during a development process it's easy to make mistakes, so the Monitoring > Health checks are great. We found a new pattern we'd love to have added there to avoid human errors.

We'd like a check for Invalid Groups Ids that a Product is related with.
In other words, the following query should return 0 for everything to be OK
`SELECT count(GroupProductRelationGroupId) FROM EcomGroupProductRelation WHERE GroupProductRelationGroupId NOT IN (SELECT GroupId FROM EcomGroups)`

The name for it could be "Broken Group Product relation references" with the description "References in Ecommerce tables to non-existent GroupIds"

There is a similar check called "No GroupId in product-group relation", but that only checks for empty GroupIds. It could also be extended to consider invalid Groups Ids

Could this be added to DW9 and DW10?

**Comment by nicped** [comment]
Thank you for the thorough description and suggestion. This will be in 10.5 and next release of the health providers provider for DW9
devops#19483.

**Comment by nunoaguiar** [comment]
Hi Nicolai,

Thank you. Along the same line, we came across 2 other queries just this morning that would be beneficial as well. I'm happy to open another Feature Request if that's better.

"**Broken Shop Group relation references**" with the description "**References in Ecommerce tables to non-existent GroupIds in Shops, Warehouses and Channels**"
`SELECT * FROM ecomshopgrouprelation where Shopgroupgroupid NOT IN (SELECT GroupID FROM EcomGroups)`

"**Broken Group relation references**" with the description "**References in Ecommerce tables to non-existent GroupIds between Groups**"
```
SELECT * FROM EcomGroupRelations WHERE GroupRelationsGroupId NOT IN (SELECT GroupID From EcomGroups) OR 	
GroupRelationsParentId NOT IN (SELECT GroupID From EcomGroups)
```
