### ISSUE TITLE
Adding integration activity name to bread crumb

### ISSUE THREAD

**Issue by Wassini** [dynamicweb/DynamicWeb#31]
Would it be possible to add the name of the integration activity to the bread crumb?

![image](https://github.com/dynamicweb/DynamicWeb/assets/17749701/223c86e4-7d5c-4921-8de1-816b33682fb1)

![image](https://github.com/dynamicweb/DynamicWeb/assets/17749701/ad4b61ee-f8f6-4913-8356-2ba3911167e3)

**Comment by DynamicRas** [comment]
Hi,

It is already included. 
![image](https://github.com/dynamicweb/DynamicWeb/assets/130552435/1b0d51a1-b7f2-4db5-a008-06224b9f86a1)

BR Rasmus Sanggaard
