### ISSUE TITLE
Optimize GetTables()

### ISSUE THREAD

**Issue by nunoaguiar** [dynamicweb/DynamicWeb#33]
We got a report of the most CPU intensive queries in DW9 (multiple databases), after having had a lot of performance issues. and this one was referenced multiple times.
**SELECT * FROM Information_Schema.Tables WHERE Table_Type = 'BASE TABLE'**

I did a very quick inspection on the code, but sounds like we can optimize it by simply querying the **TABLE_NAME** column
**SELECT TABLE_NAME FROM Information_Schema.Tables WHERE Table_Type = 'BASE TABLE'**

I also see this in DW10's source code, so it could be an improvement for both versions.

I want to be clear that our performance issue was a sum of little things. This is just one of them.

Best Regards,
Nuno Aguiar

**Comment by nicped** [comment]
Implemented on DW10, https://dev.azure.com/dynamicwebsoftware/Dynamicweb/_workitems/edit/20496
