### ISSUE TITLE
ECOM/PIM: Content Container for use with global elements for e.g. product detail pages and other web pages.

### ISSUE THREAD

**Issue by lhodynamicweb** [dynamicweb/DynamicWeb#37]
**Is your feature request related to a problem? Please describe.**
A central global content container that can be inserted into various elements across solutions.
These must be able to be written and translated into other languages.
When the text is changed in the global content container, all the places where it is used will also be updated.

**Describe the solution you'd like**
The principle is exactly the same as the PIM, where data is managed centrally, but updated globally.
These are just global texts that cannot be assigned to the product in the PIM.
For example delivery conditions, shipping prices, product abbreviations, Social Respoincibility, etc.
Texts that are controlled centrally, but used globally.

**Comment by nicped** [comment]
We did have this before and we will not re-introduce it. Also it is resulting in duplicate content and 

Item or query publisher can be used to publish the same content in multiple places.
