### ISSUE TITLE
Asserts - refresh 

### ISSUE THREAD

**Issue by Wassini** [dynamicweb/DynamicWeb#38]
It is not possible to manually refresh the folders under Assets. The list is not refreshed automatically.

![image](https://github.com/dynamicweb/DynamicWeb/assets/17749701/b7f2f2e7-93e2-4067-a659-9a72a1ed0a22)

**Comment by nicped** [comment]
A general tree refresh on the tree for all areas is in the works. It will be in the very top of the tree column on the 3 dots.

**Comment by Wassini** [comment]
I'm not sure where you mean

![image](https://github.com/dynamicweb/DynamicWeb/assets/17749701/4e10c614-06ff-48e0-b722-fbff20e16873)

![image](https://github.com/dynamicweb/DynamicWeb/assets/17749701/e012a49c-6a10-4160-813d-bf353acece2c)

![image](https://github.com/dynamicweb/DynamicWeb/assets/17749701/dad43781-dac4-49f3-892f-b4da99c57590)
