### ISSUE TITLE
Disable autocomplete

### ISSUE THREAD

**Issue by Wassini** [dynamicweb/DynamicWeb#4]
DW Version 9.17.3

Editing an endpoint authentication, the user fields in the form is not set to autocomplete=off.
This applies to all the user fields in the different auth types.
This causes e.g. LastPass to overwrite the field when opening the setting.

![image](https://github.com/dynamicweb/DynamicWeb/assets/17749701/5b0c2bd0-b327-4625-b605-fb03723fcaf3)

**Comment by nicped** [comment]
Lastpass does not respect autocomplete=off - we would need last-pass specific attributes to make this work - and there would still be issues with other password managers.

Would this not be a matter of changing settings for last-pass? https://support.lastpass.com/s/document-item?language=en_US&bundleId=lastpass&topicId=LastPass/disable-autofill.html&_LANG=enus

**Comment by Wassini** [comment]
This would disable LassPass on the frontend and the backend login too.

If checking this setting in LastPass, it will respect the AutoComplete=off
![image](https://github.com/dynamicweb/DynamicWeb/assets/17749701/45eb9a3e-5505-42dd-a462-87470133dbbc)

Without the setting both fields are filled by LastPass:

![image](https://github.com/dynamicweb/DynamicWeb/assets/17749701/1c6c91a4-0301-4f85-80ff-e472d260d2ed)

When set, only the name field is changed:

![image](https://github.com/dynamicweb/DynamicWeb/assets/17749701/81105124-95c1-4a98-afae-b54d5c7d30c4)

**Comment by nicped** [comment]
DW10 implements  autocomplete="one-time-code" for password fields to avoid autocompletions as good as we can.
