### ISSUE TITLE
Assortment management

### ISSUE THREAD

**Issue by dwlhs** [dynamicweb/DynamicWeb#40]
We're working on a solution that is using Assortments, and I must admit, the entire assortments management UI could use some (wast amounts of) TLC. But one thing that is blocking is selecting user for an assortment.

We have 4000+ users in the Customers group, but the user selection pane only shows the first 96 user with no searching and paging.

![image](https://github.com/dynamicweb/DynamicWeb/assets/31095845/b06e7a30-3f73-492d-9444-02c1b93bf143)

Unfortunately, the customer we're testing with is no amongst the top 96 users.

Besides, and I don't know if it's missing translations or what, but the controls on that screen are called:

- IncludeSubgroups
- AllowAnonymousUsers
- UserIds
- UserGroupIds

**Comment by nicped** [comment]
UI fixed in https://dev.azure.com/dynamicwebsoftware/Dynamicweb/_workitems/edit/19688

Search for users will be in a separate item but is also on the way.

**Comment by dwlhs** [comment]
@nicped do you have a work item and eta for the search for users? I have a customer asking for that.

Thanks :)

**Comment by nicped** [comment]
https://dev.azure.com/dynamicwebsoftware/Dynamicweb/_workitems/edit/20144
