### ISSUE TITLE
Sort shipping and payment methods

### ISSUE THREAD

**Issue by ivaigor96** [dynamicweb/DynamicWeb#43]
If the customer wants the shipping or payment methods to show up in a specific sort order on the front end, I don't see a way to do this from the interface
This ends up being a custom front end change
It would be nice if this option existed either on a Swift paragraph, or on the settings UI itself

![image](https://github.com/dynamicweb/DynamicWeb/assets/21162540/a4f5be7f-bd77-4e6f-b7d6-5cb465726048)

**Comment by DynamicRas** [comment]
Good find. I will add it to an upcoming sprint. Thnx. 

BR Rasmus Sanggaard

**Comment by nicped** [comment]
Closed with https://dev.azure.com/dynamicwebsoftware/Dynamicweb/_workitems/edit/19765
