### ISSUE TITLE
Repositories UI

### ISSUE THREAD

**Issue by dwlhs** [dynamicweb/DynamicWeb#46]
I've set up the up a couple of new indexes for testing purposes, but I've really been struggling decoding the new UI. I'm glad that I know from DW9 which objects need to be set up (builders, instances, queries, factes, etc.), but otherwise I would be lost. Some things have a tile, some things are hidden under context menus or tabs. Ctrl+S conflicts with Save on Paragraph, if you also have a paragraph open. When adding expressions to a query, the is a page refresh every time to make a selection, so you can't tab your way ahead in the fields, which is bad for productivity. If you use Ctrl + S on an expression, you are some times sent back to the main page of the repository, and a bunch of error messages are displayed:

![image](https://github.com/dynamicweb/DynamicWeb/assets/31095845/4e49afca-3cbb-4ee3-9a80-4391142f6dde)

Reopening the query reveals that all fields have been added once more:

![image](https://github.com/dynamicweb/DynamicWeb/assets/31095845/db728497-d2fa-44d3-a3ac-565d48686140)

Speaking of the repository main page, it has little or no value. There is a huge area for Tasks, and links index and query page. Clicking the Query, you arrive at a page, where you must click "Manage" to change the modify the query. When would you open the queryand not want to manage it. I realize that you click on the query to manage - why not just link that?

Hope you'll add some attention to this UI :-)

**Comment by dwlhs** [comment]
Also a bit confusing. Are the excluded fields in the "Exclude fields" list included in the index or excluded ;)

![image](https://github.com/dynamicweb/DynamicWeb/assets/31095845/decb3fa0-c12e-4988-b59d-be12ffa836c4)

**Comment by nicped** [comment]
There are changes related to this coming in 10.5.
"Excluded fields" control have been altered.
There are a number of updates for repositories on its way - the first ones in 10.5, remainder is coming as we figure out what exactly to do.
One thing you will not get though - it will not be as in DW9 :-)

**Comment by nicped** [comment]
Repo Overview:

![image](https://github.com/dynamicweb/DynamicWeb/assets/3715307/f1a2adb5-27ff-42a2-afb6-2a92044a601e)

Index overview:
![image](https://github.com/dynamicweb/DynamicWeb/assets/3715307/f1a94cab-70ad-41b5-9770-9fe9100fcca5)

**Comment by dwlhs** [comment]
I see some small ui changes, but it's difficult to tell from the sceeenshot if the handling is easier. You really need to know a lot about the repositories to be able to manage it (10.4.3). E.g. if you build the repository from the scratch (the one from the screenshot dates back from 2021, so it was probably done in DW9), there is no instance tile. If you're curious, you might click on the Actions bar and discover the "Manage instances" button. Same with parameters, they are also hidden in the actions bar.

I don't want DW9, I just don't my life to be more complitated :)

**Comment by nicped** [comment]
As I state, the above screenshots is part of the first of multiple changes. There are more coming.

**Comment by dwlhs** [comment]
Sounds good :)
