### ISSUE TITLE
Hovering over navigation tag icon should show the actual value of the navigation tag instead of "Navigation tag"

### ISSUE THREAD

**Issue by ivaigor96** [dynamicweb/DynamicWeb#47]
![image](https://github.com/dynamicweb/DynamicWeb/assets/21162540/4da7ecea-05e5-4848-ad23-eb600e3f1ce5)

Currently to check what navigation tag the page has you have to right click, open the page, switch tabs
When you hover over the navigation tag icon it just says "Navigation tag"
If this where to be changed to it's value, it would require 0 clicks to check navigation tag

**Comment by nicped** [comment]
Fixed - again! Actually the icon has a title, but also the enclosing span which holds the information you need.

Either way - fixed it now: https://dev.azure.com/dynamicwebsoftware/Dynamicweb/_git/Dynamicweb10/pullrequest/13394
