### ISSUE TITLE
Link to order receipt page if exists on order in the back end

### ISSUE THREAD

**Issue by ivaigor96** [dynamicweb/DynamicWeb#49]
When customizing or configuring or debuggin issues with the order receipt template we need a way to see it on the front end. Placing an order each time, logging in and searching for it under the customer center or finding a URL from the log are the current options we have. But what if there were a better way ?

It's possible to find the link to an order receipt on the front end by accessing the order log in the back end from the edit order actions

![image](https://github.com/dynamicweb/DynamicWeb/assets/21162540/851bf984-f007-4764-9e5f-923aba3daef4)

The URL looks something like this /Default.aspx?ID=2123&CompletedOrderId=ORDER632&CompletedOrderSecret=3d635d509a16484baf4c94985402a281

It would be a great addition to the order UI in the back end that this link was accessible somehow instead of only being in the log. Then it could be clicked and viewed, saving a lot of time.

**Comment by DynamicRas** [comment]
Hi, 

Thnx for the request, makes sense to implement. We will take a look at it in an upcoming sprint. 

BR Rasmus Sanggaard
