### ISSUE TITLE
Remember last request for BC test tool

### ISSUE THREAD

**Issue by dwlhs** [dynamicweb/DynamicWeb#50]
When using the test tool, it's commonly because you do a modification of the AL code, and you want to test or debug the modification. You do this repeatedly, and currently you have to fill in the request XML, every time you launch the page. It would be great if the test tool would remember the last request and automatically fill this in the Request field, perhaps with an option to auto post the request when launching the page.

**Comment by DynamicRas** [comment]
Hi,

Which version of the test tool are you referring to? Desktop, DW10 or inside BC?

BR Rasmus Sanggaard

**Comment by dwlhs** [comment]
The one inside BC :)

Br.
Lars

**Comment by DynamicRas** [comment]
Hi Lars,

Got ya, we will take a look at what is possible. 

BR Rasmus Sanggaard
