### ISSUE TITLE
Redirect user to start page in Swift

### ISSUE THREAD

**Issue by dwlhs** [dynamicweb/DynamicWeb#58]
Hi :)

For users and groups there is an option to redirect them to a specific page when they log in:

![image](https://github.com/dynamicweb/DynamicWeb/assets/31095845/b2f320c6-8b7d-420d-95e8-68e401e9a80a)

In the Swift login template we also observe this setting:

![image](https://github.com/dynamicweb/DynamicWeb/assets/31095845/f0ceeca0-4bbb-46ac-a116-8ec208e262ec)

I the form it seems that we

![image](https://github.com/dynamicweb/DynamicWeb/assets/31095845/eb94bbf0-edcc-4839-b312-a669f33be7b9)

But apparently, this field has been removed form the item type, so the value will always be false, and then we always send a redirect URL, and this the redirect setting on users and groups will not be effective:

![image](https://github.com/dynamicweb/DynamicWeb/assets/31095845/7c0d548a-5358-40e6-9061-5678b8a74d06)

Can we have the field back, so that we can leverage the standard redirect functionality?

**Comment by nicped** [comment]
This is a bug

I think it has been removed from Swift because the login feature should take care of this - and not Swift it self. There are some major changes in DW10 in relation to how redirects work in general (due to changes to .net)

Can you by the elaborate on what you use the field for - do different users have different start pages?

**Comment by dwlhs** [comment]
We don't use the field as we want to rely on the start pages on users/groups. But if it was removed, so we can control the start pages in User Management, I guess line 61-63 should also just be removed.

Yes, different users have different start pages. E.g., customers should be redirected to the shop frontpage or their dashboard page, and sales people should be redirected to the list of customers they can impersonate.

Br.
Lars

**Comment by nicped** [comment]
Registered as Swift bug: https://dev.azure.com/dynamicwebsoftware/Dynamicweb/_workitems/edit/19879
