### ISSUE TITLE
Implementing AVIF format for Image Handler to improve performance over what it is currently available with WEBP

### ISSUE THREAD

**Issue by daniel-voicu-dev** [dynamicweb/DynamicWeb#6]
**Describe the solution you'd like**
I would like to have a new value(format=AVIF) for the format parameter when rendering images so that it outputs AVIF files.

**Comment by nicped** [comment]
Thank you for the feature request. Currently we cannot implement this as we use an external image processing library that does not support AVIF. There are a number of potential issues supporting this format. Currently the decoder libs are in un-managed code only and we are not very keen on getting that inside a managed codebase.

Also the AVIF is a container format that potentially holds more images - or motion/video - and that is not easy to decode and encode in another format - encoding a jpg to AVIF might be relatively simple, but fully supporting AVIF is not without issues.

So for now we cannot implement this feature but will of course do it as soon as we can support in managed code.

Also we keep an eye on JXL that is a simpler alternative for fast image but still not accepted by Chrome.

**Comment by daniel-voicu-dev** [comment]
Ok. Thank you for your answer.
