### ISSUE TITLE
Text search input box in "translations" doesn't work when you press 'ENTER' on your keyboard.

### ISSUE THREAD

**Issue by ArtjomJensen** [dynamicweb/DynamicWeb#60]
![image](https://github.com/dynamicweb/DynamicWeb/assets/42613107/6f5a1d1b-f6c2-4ea1-828e-6991dae2457f)

It would be nice if I could press 'ENTER' after writing my search query.

**Comment by dw-jea** [comment]
This is supposed to work already. I have just tested it, and there seems to be an issue with Firefox. It works as expected in Chrome and Edge.

I have registered it as a bug: https://dev.azure.com/dynamicwebsoftware/Dynamicweb/_workitems/edit/20102
