### ISSUE TITLE
Enabling assortments

### ISSUE THREAD

**Issue by dwlhs** [dynamicweb/DynamicWeb#61]
Hi :)

Assortments are managed in Commerce:

![image](https://github.com/dynamicweb/DynamicWeb/assets/31095845/b2d5b3bb-8f46-470a-bfd1-f12ac7213574)

However, the toggle to switch assortments on and off is placed in Products:

![image](https://github.com/dynamicweb/DynamicWeb/assets/31095845/e0ab16bc-cb73-46d7-9ced-e7b4338cbe47)

It would be logical to move it under Commerce, so it follows the main structure.

**Comment by DynamicRas** [comment]
Hi Lars,

We will move it to Commerce - Advanced Configuration instead.

BR Rasmus Sanggaard
