### ISSUE TITLE
Search in Users

### ISSUE THREAD

**Issue by dwlhs** [dynamicweb/DynamicWeb#62]
Hi :)

It seems that the search in Users only searches for users in the current group. We're working on a solution where currently we have 3300 groups of customers in three levels, and looking individual customers/contacts is extremely difficult if you don't know, where they are located.

A global search button on Uses will be very useful.

Br.
Lars

**Comment by ivaigor96** [comment]
https://github.com/dynamicweb/DynamicWeb/issues/14
