### ISSUE TITLE
Behavior in Data Integration

### ISSUE THREAD

**Issue by dwlhs** [dynamicweb/DynamicWeb#63]
Hi :)

In Data Integration, when you add a new table mapping, where the field can't be mapped automatically, it adds mappings for source fields and not destination fields (of cause), but then it sets the mapping to inactive:

![image](https://github.com/dynamicweb/DynamicWeb/assets/31095845/14ed164c-db88-4471-9f05-5d7c9269b042)

You must then set the destination fields, but if you are not aware of the mappings being inactive, the provider runs into an exception:

![image](https://github.com/dynamicweb/DynamicWeb/assets/31095845/aa948160-03cf-4375-b9a2-88d25ac9734d)

There are two things here:

1. If the mappings are in active, this should be handled more gracefully, e.g., skipping the mapping
2. There is no reason to deactivate the mappings, as the person setting up the integration probably intends to map to a destination, so just set them as active even though the destination mapping columns can't be resolved automatically.

Enjoy :)

**Comment by DynamicRas** [comment]
Hi Lars,

I think we will stick to the flow as it is, but it shouldn't make an exception just because some rows are inactive. So please report that bug with a detailed description. 

BR Rasmus Sanggaard
