### ISSUE TITLE
Ability to edit HTML in rich text fields

### ISSUE THREAD

**Issue by Justinvolved** [dynamicweb/DynamicWeb#64]
When I need to do a bit more advanced alignment of text, the richt text editor does not provide enough options.

I would like to be able to edit the underlying source HTML.

As an example I would like to use this in the footer, where there is text around opening hours which reads "Monday-Friday 9:00-17:00" where the first part should be aligned left, and the second part aligned right, for example like:
<p style="text-align: left; width: 50%;">Monday-Friday</p>
<p style="text-align: right; width: 50%;">9-17</p>

**Comment by nicped** [comment]
The editor will get new features so you can configure it your self at some point. It is Quill so the options it has you can use.
