### ISSUE TITLE
See user and group type from the edit / details screen

### ISSUE THREAD

**Issue by ivaigor96** [dynamicweb/DynamicWeb#66]
Currently I can not find a way to see which user and group type the user belongs to except in the list view

![image](https://github.com/dynamicweb/DynamicWeb/assets/21162540/9f7a5418-8c1c-4ea7-8a50-6e9fb95ccd28)

It would be nice if we could also see this value somehwere in the details / edit screen

![image](https://github.com/dynamicweb/DynamicWeb/assets/21162540/307eba0c-a9d1-4e89-b1ac-541feeb2813f)

**Comment by nicped** [comment]
devops#20155
