### ISSUE TITLE
Open list view instead of visual editor when clicking on a page

### ISSUE THREAD

**Issue by ivaigor96** [dynamicweb/DynamicWeb#67]
![image](https://github.com/dynamicweb/DynamicWeb/assets/21162540/a7fcb7b6-1c43-4cea-8f3b-642741201b5c)

It would be great if there was a setting for your user which view opens when clicking on a page in DW10
Only for content enrichment users does it make sense that the visual editor opens as default view
It should be possible to set that the list view opens when clicking instead
Right now, I always want to the list view, I never use the visual editor, and this makes the UX horrible as I have to use this actions bar each time I want to enter the list view

**Comment by dw-jea** [comment]
There is such a setting already.

Go to Settings -> Content -> Interface settings. There you'll find a checkbox for _Show list for visual editor based pages_. If the Content area already loaded, you need to reload it. It's a small quirk with the current implementation.
