### ISSUE TITLE
Open file edit, not file properties when clicking on txt, cshtml, csv, xml file in the Files UI

### ISSUE THREAD

**Issue by ivaigor96** [dynamicweb/DynamicWeb#68]
When clicking on a file it will open the file properties screen

![image](https://github.com/dynamicweb/DynamicWeb/assets/21162540/8bc9060a-2528-484d-8023-fbd0e7593d9b)

This screen is useless, i just shows you the same information that you already saw in the list view, when clicking on a file it should instead just open the edit screen

I understand this way of thinking with users, products or other screens where there is more information and actions
But for a file, it should not open this details screen and go to edit screen first
How it works right now, it just feels bad to use the platform

**Comment by nicped** [comment]
This has already been fixed and released. Devops#18203
