### ISSUE TITLE
Missing fields in Order overview

### ISSUE THREAD

**Issue by Wassini** [dynamicweb/DynamicWeb#7]
In DW10 in the backend under Commerce and Orders, it is not possible to add columns I need, like: Total price (without VAT) or Integration Number

**Comment by DynamicRas** [comment]
Hi, 

The total price ex VAT is in the Order Totals widget. 
Or where is it exactly would are missing it? Is it in the order lines list widget? 
What is the use case for showing integration number, to find the corresponding order in ERP?

BR Rasmus Sanggaard

**Comment by Wassini** [comment]
Ah. Sorry... Its in the order list.
![image](https://github.com/dynamicweb/DynamicWeb/assets/17749701/dffe879a-2d09-4561-98fc-01c8967398e1)

**Comment by DynamicRas** [comment]
Ah oki, makes sense. We will add them in one of the following sprints. Thanks. #18892

BR Rasmus Sanggaard
