### ISSUE TITLE
Performance issue in assortment details

### ISSUE THREAD

**Issue by dwlhs** [dynamicweb/DynamicWeb#71]
Hi :)

One of our customers has created an assortment containing all their customers. When clicking the Edit button:

![image](https://github.com/dynamicweb/DynamicWeb/assets/31095845/892bf495-0696-40b8-b252-9a71a3d586d4)

The page hangs for some 9 minutes, probably to generate the content of the Users control, before it eventually loads:

![image](https://github.com/dynamicweb/DynamicWeb/assets/31095845/254e6709-b9a1-491e-a636-3ce63f05e2c9)

Admittedly, there are 6500 user associated to the assortment, but the question is if the control could handle this in another way, e.g., paged, or a "see more" that loads a modal, where the user can page through the list and search/filter.

Br.
Lars

**Comment by nicped** [comment]
Nope...

I will bug it instead.

We will change it to throw an exception - or a big fat warning.
Adding this many single users will also cause issues in the frontend, so you have to change your implementation.
Users should be added to a group instead and that group used for the assortment.

**Comment by nicped** [comment]
20157

**Comment by nicped** [comment]
Moved to bug: https://dev.azure.com/dynamicwebsoftware/Dynamicweb/_workitems/edit/20157
