### ISSUE TITLE
Search functionality in user control

### ISSUE THREAD

**Issue by dwlhs** [dynamicweb/DynamicWeb#73]
Hi :)

Received input from a customer regarding the user control in Assortments (and in general, I guess). The claim was that it was difficult to use for verifying which users are attached, as it doesn't contain search or sorting. They have over 6500 users attached to this assortment.

![image](https://github.com/dynamicweb/DynamicWeb/assets/31095845/6dbe0707-94af-4f69-91f8-a28f44dd1140)

Enjoy :)

Br.
Lars

**Comment by nicped** [comment]
As written in another post - create a group for the assortment and use usermanagement to add new users.
All users node with search is on its way.
