### ISSUE TITLE
Improvement to scheduled task - sub tasks

### ISSUE THREAD

**Issue by dwlhs** [dynamicweb/DynamicWeb#74]
Hi :)

In troubleshooting scenarios it would be great to be able to run the sub tasks individually from the context menu, so we can step through the subtasks one by one.

![image](https://github.com/dynamicweb/DynamicWeb/assets/31095845/f670e0c4-f891-4617-b4a4-e00c3beecd07)

Br.
Lars

**Comment by Justinvolved** [comment]
+1

**Comment by DynamicRas** [comment]
Hi,

Makes sense, we will add it.

BR Rasmus Sanggaard
