### ISSUE TITLE
Add logging to RemoveNoneActiveProducts

### ISSUE THREAD

**Issue by Justinvolved** [dynamicweb/DynamicWeb#75]
I seem to have an issue where orderlines are removed during checkout. The actual removal of productlines is probably by design in dw, and caused by the fact that some products are temporarily InActive (won't go into the boring technical ERP connection details here ;-))

It was a difficult issue to pinpoint, and I think logging the actions of the RemoveNoneActiveProducts function would make sense. 
There are multiple conditions that will cause OrderLines to be removed, and I think that should be logged to the Order Log.

https://dev.azure.com/dynamicwebsoftware/Dynamicweb/_git/Dynamicweb10?path=/src/Features/Ecommerce/Dynamicweb.Ecommerce/Orders/OrderService.cs&version=GBmaster&line=1032&lineEnd=1033&lineStartColumn=1&lineEndColumn=1&lineStyle=plain&_a=contents

**Comment by nicped** [comment]
devops#20151
