### ISSUE TITLE
Confusion in sort column mappings in Integration

### ISSUE THREAD

**Issue by dwlhs** [dynamicweb/DynamicWeb#76]
Hi :)

When using script values in mappings, the sorting feature apparently remembers which source field was selected before the script value option was added. In the screenshot below, the circled columns are actually constants, but they appear as column mappings:

![image](https://github.com/dynamicweb/DynamicWeb/assets/31095845/2f3fbc1a-614c-4806-8d62-faa32d28ad20)

It would be great if the list could show the type and value of the script value, e.g., "Constant: LANG".

Br.
Lars

**Comment by DynamicRas** [comment]
Hi,

Good find. We will fix it. 

BR Rasmus Sanggaard
