### ISSUE TITLE
Show mapping descriptions on integration overview

### ISSUE THREAD

**Issue by dwlhs** [dynamicweb/DynamicWeb#77]
Hi :)

I added descriptions to the table mappings in this activity. It would be great if they were shown on the "Mappings" widget:

![image](https://github.com/dynamicweb/DynamicWeb/assets/31095845/16571f92-5674-4fb1-8052-ca32c5b07951)

Thanks :)

Br.
Lars

**Comment by nicped** [comment]
devops#20163 - added.
