### ISSUE TITLE
Improved visibility of missing activity files

### ISSUE THREAD

**Issue by dwlhs** [dynamicweb/DynamicWeb#79]
Hi :)

In Scheduled Tasks, subtasks with missing activities are listed fine, but it's not until you open the subtask that you notice that the activity file is missing:

![image](https://github.com/dynamicweb/DynamicWeb/assets/31095845/c7499b0b-609b-4262-ae5f-70a9190f17fd)

It would be nice to show an indication of this in the list.

Thanks :)

Br.
Lars

**Comment by DynamicRas** [comment]
Hi,

Makes sense, we will take a look at how to show that the files are missing in the list as well.

BR Rasmus Sanggaard
