### ISSUE TITLE
Can't move activities to root folder

### ISSUE THREAD

**Issue by dwlhs** [dynamicweb/DynamicWeb#80]
Hi :)

I want to move an integration activity to the root of "Activities" to work around bug in the task scheduler. But In the UI I can only move it inside a folder and not to the root:

![image](https://github.com/dynamicweb/DynamicWeb/assets/31095845/fc57fa89-3df1-42ac-9254-6595c97848ae)

I can move it in Assets, but it would be nice to be able to do it in the Integration UI.

Br.
Lars

**Comment by DynamicRas** [comment]
Hi,

Thanks. We will take a look at what is possible.

BR Rasmus Sanggaard
