### ISSUE TITLE
Scheduled task jumpy interface

### ISSUE THREAD

**Issue by dwlhs** [dynamicweb/DynamicWeb#81]
Hi :)

When running a scheduled task, the log appears in the bottom. The page refreshes every second or so, so when you scroll down to inspect the log, the page is refreshed, and you see the top of the page again.

It would be nice if it would remain in the bottom, or perhaps was displayed like the log, when running an integration activity.

Br.
Lars

**Comment by DynamicRas** [comment]
Hi,

We don't have the possibility to refresh only certain items in the UI. If you have troubleshooting, you can run the job from the mappings screen and get the running log in the output viewer.

BR Rasmus Sanggaard

**Comment by dwlhs** [comment]
I know, and it's sad. But the scroll height can be remembered like in the Integration mappings. Maybe it's a platform thing rather than an integration thing.

Br.
Lars

**Comment by DynamicRas** [comment]
Hi,

Yeah, it is a platform thing and automatically jumping down to the last scroll position when the page refreshes each 2nd second would be a very jumpy experience, we don't want that. 

BR Rasmus Sanggaard

**Comment by dwlhs** [comment]
Sad to hear that it can't be improved.

Br.
Lars

**Comment by DynamicRas** [comment]
The feature request is noted, the specific solution is declined :)

BR Rasmus Sanggaard

**Comment by dwlhs** [comment]
Oh joy :)
