### ISSUE TITLE
Admin UI products screen - sort by any column

### ISSUE THREAD

**Issue by ivaigor96** [dynamicweb/DynamicWeb#83]
Currently it's possible to click on product name and number and then it will sort ascending or descending on that value
![image](https://github.com/dynamicweb/DynamicWeb/assets/21162540/f8883c32-dc7c-4690-8f0d-6c02b48c6e89)

But it would be extremely helpful if we can do this on all columns
The interesting thing is that it's already supported by the URL, so for example sorting by the discontinued column works if I changed the field in the URL

Admin/UI/Products/ProductList?PagingIndex=1&PagingSize=96&SortColumnName=**Discontinued**&SortDirection=descending&Type=ProductsAll

So this is some sort of UI limitation only

**Comment by nicped** [comment]
https://dev.azure.com/dynamicwebsoftware/Dynamicweb/_workitems/edit/20492

**Comment by nicped** [comment]
Most columns can be sorted with this change.
