### ISSUE TITLE
Stock State in Swift

### ISSUE THREAD

**Issue by Wassini** [dynamicweb/DynamicWeb#85]
There are 2 feature requests here:

**Minor request:**
Swift will show "Out of stock" as a hard coded value when the stock is 0 even if the stock state is not setup. There should be a setting that enables this this text - and otherwise show 0 (or the actual stock value). This is just a minor request.

**Major request:**
Setting up stock state is not working as expected: Adding a stock state to the shop or the product group does nothing for existing products in that group. 
How I would expect this to work: A product should use the stock state set on the product. If this is not present, it should look at the group, the parent group and last at the shop for the setting.

Right now it is not possible to set a stock state on a group and use this on the front end without have to make a script that updates all products in the database.
Also it makes the product import more complicated, as we have to take the stock state setting into account when importing.

**Comment by jentjohansen** [comment]
Hi Wassini

When adding stock state on an existing product group with existing products, you need to force its inheritance so the products will get this stock state information.  you can do that by clickingon this icon, then you do not need to run a script to update the products in the database

![image](https://github.com/dynamicweb/DynamicWeb/assets/87016953/67bc49b3-9999-4593-9b0a-59c3a65ba67e)

**Comment by nicped** [comment]
I can add to this that the section is named "Default values for new products" generated in the UI.
It cannot inherit these information because products can belong to many groups with potential different settings. So it has to be specified on the product it self

**Comment by lbw-dynamicweb** [comment]
@nicped:
> I can add to this that the section is named "Default values for new products" generated in the UI. 

Not in DW10 ;-)
![image](https://github.com/dynamicweb/DynamicWeb/assets/167293746/569a33c6-246b-432b-b673-8f366895397d)

**Comment by lbw-dynamicweb** [comment]
@jentjohansen:
> When adding stock state on an existing product group with existing products, you need to force its inheritance so the products will get this stock state information. you can do that by clicking on this icon, then you do not need to run a script to update the products in the database

This icon is not present in DW10, so when the user changes the default stock state, they need a script to change all the products in the group.
I also need a script, because importing new products needs to set it on the imported product.

**Comment by lbw-dynamicweb** [comment]
@nicped:
> It cannot inherit these information because products can belong to many groups with potential different settings.

But there is only ONE default group on a product.
