### ISSUE TITLE
Improved error messaging

### ISSUE THREAD

**Issue by dwlhs** [dynamicweb/DynamicWeb#88]
Hi :)

In Integration when attempting to import from a file that doesn't exist, the system logs a very strange error:

![image](https://github.com/dynamicweb/DynamicWeb/assets/31095845/62ed5399-d3e5-42c9-b595-59941cc6c766)

It would better to catch that the file doesn't exist at an earlier state in the process and then add this information to the log.

Br,
Lars

**Comment by DynamicRas** [comment]
Hi, 

Agree, I have created a task for this and one for a more general run through of error messages to have a more meaningful message. 

BR Rasmus Sanggaard
