### ISSUE TITLE
Edit multiple users groups

### ISSUE THREAD

**Issue by lbw-dynamicweb** [dynamicweb/DynamicWeb#89]
It seems that when using the "remove from group" is only possible to remove selected users from the current group (like in DW9), but in DW9 is was also possible to use the "Add to group" to remove a group. In DW10 this option is no longer possible!

I would suggest that the "Add to group" and "Remove from group" is replaced by a "Manage Groups" where it should be possible to add and remove groups instead.

**Comment by nicped** [comment]
Not sure I follow. You have forgotten to specify where you are in the UI - but based on the actions you mention, I guess the list of users.

The users in the list can be member of different groups - so a manage for a list of users with different sets of group relations will not make sense. The actions you refer to, are list actions - meaning you can select many users in the list and perform the actions.

If you go into a single user and choose manage groups, you get what you seek. But only for one user at a time.

**Comment by nicped** [comment]
Added link to manage groups from user list on the user actions
https://dev.azure.com/dynamicwebsoftware/Dynamicweb/_workitems/edit/20251

**Comment by lbw-dynamicweb** [comment]
Sorry! Yes - it's the user list.

In DW9 you can select more users and then "Add group", where it is possible to add/remove groups for all users:
![image](https://github.com/dynamicweb/DynamicWeb/assets/167293746/c202d7c3-aec1-490a-b525-2b8322a42725)

I see the problem if the users are in different groups. I don't know how this was handles in DW9.

My problem is that sometime users are placed in 2 groups and I want to remove the 2nd group from 50+ users. (I can off cause do it using SQL)

**Comment by nicped** [comment]
You can remove 2nd group from 50+ users. Just go to the group and use the list actions in the "Actions" button in top of the list screen

**Comment by lbw-dynamicweb** [comment]
I have 2 groups:
Group 1 with 50 users.
Group 2 with 500 users.
Now I want to remove all users in group 1 FROM group 2.

**Comment by nicped** [comment]
Go to group 1 and remove them
