### ISSUE TITLE
Catch null references, and display a meaningfull error

### ISSUE THREAD

**Issue by Justinvolved** [dynamicweb/DynamicWeb#91]
There are may places in Swift where this is applicable, as an example I'll describe setting up a new e-mail header and footer here.
When I create a structure like this, the process of getting it to work is not that intuitive, which would be less of a problem if some null references are handled. 
![image](https://github.com/dynamicweb/DynamicWeb/assets/64196420/68d6d0d2-3baa-4ec3-91d9-9ce70c3c98ac)

In this example I have created the  Emails>Newsletter Layout>Header and Footer items. I have to go back to the Newsletter Layout, and reference the header and footer (which especially for someone not very familiar with dw, is counterintuitive to begin with)
![image](https://github.com/dynamicweb/DynamicWeb/assets/64196420/11f4ce1c-ef76-48c4-81e9-275749c6fef6)

When I forgot to do this, the template crashes.
![image](https://github.com/dynamicweb/DynamicWeb/assets/64196420/eac26c8c-c04b-43ea-b6ad-6a40b1043480)

If the template would check for a null reference, and show a message that I need to set the header and footer on the parent item, it would probably save many people a few hours :-)

As mentioned, there are very many places in Swift where this happens, and it is often a big hassle to find out which setting you have missed resulting in a lot of wasted time.

**Comment by nicped** [comment]
Yes - we have an eye on this generally. Will mostly be part of Swift 2.
