### ISSUE TITLE
Comment field on subtask

### ISSUE THREAD

**Issue by lbw-dynamicweb** [dynamicweb/DynamicWeb#92]
When creating a scheduled task and adding subtasks, a field for a comments could be nice to have.

![image](https://github.com/dynamicweb/DynamicWeb/assets/167293746/a6258c6c-9ba4-42ac-b50e-d4bcdebbc386)

**Comment by DynamicRas** [comment]
Hi, 

Please elaborate a bit on the specific use case for the comment field on subtasks.

BR Rasmus Sanggaard

**Comment by lbw-dynamicweb** [comment]
It's a nice to have feature, but if I create a task containing several different SQL statements, it would be nice to make a note in the list, that shows what the subtask is about. Now I have to click on it and read the SQL and try to figure out what it does and why it is needed.

**Comment by DynamicRas** [comment]
Hi,

Thank for the explanation. We will take a look at it.

BR Rasmus Sanggaard
