### ISSUE TITLE
Assortment overview

### ISSUE THREAD

**Issue by lbw-dynamicweb** [dynamicweb/DynamicWeb#93]
When working with assortment, it is not consistent design, that I have to press "Edit" in the "information" tile, when I want to edit the users and user groups.
This should be on the overview page like the products and product groups:
![image](https://github.com/dynamicweb/DynamicWeb/assets/167293746/3def760c-dcb0-4020-92fa-3eb0b1a63539)

**Comment by DynamicRas** [comment]
Hi,

Good point. We will take a look at how to move this to the overview instead.

BR Rasmus Sanggaard
