### ISSUE TITLE
Stock State for "Never out of stock"

### ISSUE THREAD

**Issue by lbw-dynamicweb** [dynamicweb/DynamicWeb#95]
We are missing a way to set stock state for products that have the "Never out of stock" set so we can show e.g. "In stock" even if the stock value is 0.

Now it just shows nothing: 
![Skærmbillede 2024-06-28 124527](https://github.com/dynamicweb/DynamicWeb/assets/167293746/66132421-1b9a-44fe-a9cb-19e9f1ad8a6a)

### This is the setting on the product:
![image](https://github.com/dynamicweb/DynamicWeb/assets/167293746/99b069f7-6397-48e4-97bf-30a0be1ef748)

### The Stock State setting:
![image](https://github.com/dynamicweb/DynamicWeb/assets/167293746/5a4bfea1-f41e-480e-a296-2e424c8f2f94)

**Comment by nicped** [comment]
On the The Stock State group we could add a "Never out of stock" message
