### ISSUE TITLE
Multiple auto checking patterns for auto checking assets to products in Asset Categories

### ISSUE THREAD

**Issue by barendmosch** [dynamicweb/DynamicWeb#98]
Hi there,

When implementing a PIM system with automated asset-product assignation, the auto checking assets to products based on a pattern (productId, productnumber etc) is very useful for 1 to 1 or many to 1 asset product mapping. But this requires the assets to be named in a consisting and set way, i.e. "{ProductId}_Inspiration_.jpg" otherwise the task can't assign the assets to the corresponding products.

This limits the creativity of the patterns. For example, a certain PIM group might want to check the assets to products based on a certain dimension category field (i.e. width_bicycles) which is not relevant for other categories.

Using category fields or fields that are relevant for a certain amount of products in an asset category limits the patterns that can be used. For example, for the Images Asset Category the following pattern is made:
![image](https://github.com/dynamicweb/DynamicWeb/assets/38426052/4d81d066-5325-4c82-8e79-a485ac9245e1)

The Colour field in defined as a category field, since its irrelevant for some products in the PIM, for the other products we would like **to check with another pattern, but in the same asset category.**
![image](https://github.com/dynamicweb/DynamicWeb/assets/38426052/5a5b6794-1017-48b8-8180-49c2ec02b04d)

The feature request/question would be:
Is it possible to add conditions or even multiple patterns in the same asset category?

The alternative for us would making an extension on the auto assignment by adding more patterns.

Thanks in advance & kind regards,

Barend Mosch, Bluedesk

**Comment by V-L-E** [comment]
Hi,
it should be possible to use multiple patterns by concatenating them with ";"
e.g. 
{ProductFamilyName}_{ColourCategoryA}_;{ProductFamilyName}_{ColourCategoryB}_

Best regards, VIktor.

**Comment by nicped** [comment]
Already possible :-)
