### ISSUE TITLE
Improvement to Integration mapping screen

### ISSUE THREAD

**Issue by dwlhs** [dynamicweb/DynamicWeb#99]
Hi :)

When reviewing a larger mapping activity, it can be a bit tricky to distinguish missing mappings from scripts (constants e.t.c.) as they appear the same in the source column, and the script indicators are all the way to the right:

![image](https://github.com/dynamicweb/DynamicWeb/assets/31095845/4d4ca43b-53bb-48dd-a7b7-42b793743169)

It would be more intuitive to have information regarding the source data in the source column, e.g., with some sort of visual indicator that this is a script source mapping and not just a source column mapping. That would also release some real estate in as the "Script type" and "Script value" could be removed:

![image](https://github.com/dynamicweb/DynamicWeb/assets/31095845/2d062a47-d2d8-4028-acba-4a1a2629fe31)

Br.
Lars

**Comment by DynamicRas** [comment]
Hi,

Could make sense. We will take a look at what is possible. 

BR Rasmus Sanggaard
